### ISSUE TITLE
multi-window support

### ISSUE THREAD

**Issue by keen99** [glushchenko/fsnotes#1006]
**Describe your feature request**

I'd love to see the ability to open multiple windows of fsnotes - the whole 3 panel view.   I'm often looking at a note while editing it further on, or looking at other notes as references while working on another one.

I may have a window open in a workspace where my email and notes are, and pull another window into a workspace where I'm working on a project.....  and another next to my browsers.

I saw another issue requesting the ability to open the editor in a new window - also a useful feature.  https://github.com/glushchenko/fsnotes/issues/301

thanks for your hard work on this - I'd love to spend more time with it, but....being stuck in a single window is a killer for me. :)

**Additional context**
this is macos/desktop specific - obviously the IOS UI would limit this ability. :)

**Comment by arcoletge** [comment]
I think that can be possible on mac and ios, it will be very helpfull

**Comment by nth-chile** [comment]
+1 for this! Currently, it's helpful that double-clicking a note opens it with TextEdit, but what if it opened another FSNotes window with the sidebars hidden? You would still be able to open the sidebars in the new window, but they could default to collapsed ... unless you pressed a button or hotkey that opens a blank new window. In that case, sidebars would be open with no note selected (or whatever happens when you launch FSNotes)

**Comment by bumper314** [comment]
+1

**Comment by glushchenko** [comment]
Will be implemented in FSNotes 6 ;-)

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
