### ISSUE TITLE
Checkbox - [ ] does not autoconvert

### ISSUE THREAD

**Issue by ShiftyBlock** [glushchenko/fsnotes#1060]
**Describe the bug**
The - [ ] does not convert into a textbox as you type, you either click it or do command backtick to get it correct.
**To Reproduce**
1. Go to a notepad.
2. Click on the - key, space, [ key, space, ] key, space.
3. See error, which is that the checkbox does not automatically convert.

**Expected behavior**
The textbox should automatically convert.

**Actual behavior**
A clear and concise description of what actually happens.
It does not, and stays as text.

**Workaround**
A clear and concise description of any workarounds.
Command backtick

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.
<img width="299" alt="Screen Shot 2021-01-27 at 11 14 42 PM" src="https://user-images.githubusercontent.com/56007659/106103221-71f3f700-60f5-11eb-92bd-a3f47e74006d.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.6
 - FSNotes version: 3.8.2
 

**Additional context**

**Comment by glushchenko** [comment]
Bug? Really? :-/ 

Why should i do this at all?  There are shortcuts for Todo.

**Comment by ShiftyBlock** [comment]
ok but like every other markdown thing that you implemented autoconverts, and this one doesnt -> is that not glaring?
if you don't want to, up to you, but it just struck me as odd.

**Comment by glushchenko** [comment]
Like other md things, Todo not autoconverts.

**Comment by gingerbeardman** [comment]
When I edit my todo lists, I press enter at the end of the last item and it gives me a new item already with the rendered checkbox. Might be worth trying to do that?

**Comment by glushchenko** [comment]
⌘ - T useful IMO

**Comment by stefandesu** [comment]
While ⌘T is definitely useful, I do agree that `- [ ]` should be converted automatically. My main argument is that if you type it, switch the note and switch back, then it's converted. This to me feels like a UI inconsistency (because one moment it's not converted, the next it's converted).

If I type `~~test~~`, the text "test" will also be automatically shown as strikethrough. In my opinion, it's the same for checkboxes.

(However, this really is a minor thing, so if it's not important to you, leave it to someone else to implement. 😉)

**Comment by glushchenko** [comment]
Dupe #895
