### ISSUE TITLE
Dragging to another app deletes selected text

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1095]
**Describe the bug**
Dragging selected text from FSNotes to another app moves it, instead of copying it.

**To Reproduce**
1. open a new text window in BBEdit
1. edit a text note in FSNotes
2. select some text
3. drag it to the BBEdit window

**Expected behavior**
The text shows up in BBEdit. No changes in FSNotes.

**Actual behavior**
The text shows up in BBEdit. The selected text disappears from FSNotes.

**Workaround**
Use copy and paste.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.8
 - BBEdit version: 13.5.4

**Additional context**
So far I could not reproduce this with apps other than BBEdit. I assume it just implements more pasteboard types than most.

It does not matter which app is in the background when starting the drag'n'drop.

**Comment by glushchenko** [comment]
Hi, @tewe!

I dont think that this behaviour related to FSNotes, same with BBEdit + TextEdit, BBEdit + Sublime Text, etc. Seems like this implemented is BBEdit.

**Comment by gingerbeardman** [comment]
- I can confirm this behaviour dragging from FSNotes to BBEdit, and from Sublime Text to BBEdit. 
- The problem is not present dragging from FSNotes to Sublime Text.
- It's not possible to drag text onto FSNotes?

It's strange that BBEdit defaults to move the text. It should default to copy to comply with macOS HIG. Even the BBEdit manual says that it should copy text in this scenario. Indeed, it does do with its own windows but not with external windows.

> **Drag and Drop**
Another way to move text from one place to another is by “drag and drop.” If you drag and drop text from one window to another, BBEdit copies the text to the target window without removing it from the original window.

Solution:
To copy the text hold the option/alt key during the drag and drop.
This is a standard macOS convention and can be found in macOS Help files.

**Comment by glushchenko** [comment]
Thanks, @gingerbeardman

**Comment by tewe** [comment]
Forgive me for suspecting the issue in the program that's less than 25 years old. I'll ask Bare Bones if maybe this was the norm on MacOS 9.

**Comment by gingerbeardman** [comment]
@tewe I'm interested in their reply!

**Comment by tewe** [comment]
[BBEdit 13.5.6 Release Notes](https://www.barebones.com/support/bbedit/notes-13.5.6.html)
> Fixed bug in which dragging text from another application without holding the Option key down would, at the originating application's sole discretion, delete the text in the original.
