### ISSUE TITLE
SECURITY ISSUE: Secret values stored in plain text

### ISSUE THREAD

**Issue by Garbee** [glushchenko/fsnotes#1428]
# Request

When storing secrets, the value must at least be stored in an encrypted manner. Preferably in the OS Keychain to prevent it leaking to any other apps or loggers running on machines.

## Additional context

Just looking in the plist file for the app reveals the token stored under `gitPassword`. Since there is also a `gitPasspharse` string, I'd imagine that value also is being stored in plain text when it absolutely should not be.

Leaving secrets in plain text on the filesystem exposes major security concerns since any other apps, including things like install scripts from package managers, could scan for and exfiltrate the content.

EDIT:

Also, I apologize for making this disclosure in public. However the repository has no clear way to get in touch about security problems (or any real way to get in touch out of public for that matter.) You may want to consider a `security.md` file to setup a security policy for the project.

**Comment by glushchenko** [comment]
The headline here is too yellow. For git to back up we need that key, and if it's stored in encrypted form, we can't use it. 

We can ask for it every time we run the program, or request it from the keychain and store it in memory, but I see no problem pulling it out of memory, just as I do from disk.

Have you heard anything about sandbox? The keys are stored in an application container which cannot be accessed from third party applications.

If you have any ideas on how to make automatic backups without constantly asking for a password, then I will be happy to pull request. Otherwise, just don't use the backup.

**Comment by Garbee** [comment]
I don't know what you mean by you'd need to ask for the password to the keychain every time the app is opened. Chrome, Raycast, Parallels, Setapp, Steam, VSCode, etc. all store data in the keychain and you don't need to put in a password every time you open them. The keychain is unlocked with the device, and only certain items in it require a password individually as requested by the developer storing said data.

`kSecAttrAccessibleWhenUnlocked` is the Keychain class (or whatever this is) that you're looking for. Ref: https://support.apple.com/guide/security/keychain-data-protection-secb0694df1a/web . It makes things accessible when the device is unlocked and shouldn't require a password.

The way you do this is, store the private data in the keychain. You do NOT store it in memory when the app is opened. You call to the keychain when you need the data, use it, and don't store it. Security issue solved as then unencrypted sensitive data isn't laying about on the filesystem.

**Comment by glushchenko** [comment]
This only works when the Keychain is open, but then what's the point if it's always open? Your keys are also not protected in any way. Do a pool request, and I'll prove to you that it's a useless request.
