### ISSUE TITLE
External folders do not show subfolders

### ISSUE THREAD

**Issue by tjatjagithub** [glushchenko/fsnotes#1604]
### Description

After adding an external folder from iCloud, I can see files, but I cannot see subfolders and the documents within those subfolders.

Other Apps that support this, do show them.

### FSNotes version

latest

### macOS/iOS version

latest iPadOS

**Comment by tjatjagithub** [comment]
Any new information?

Is it a bug, did I do something wrong, is this just not supposed and planned to work?

**Comment by glushchenko** [comment]
This is not a bug.

**Comment by Amparose** [comment]
Given that the desktop app supports subfolders and it is not stated otherwise that the iOS app doesn't, I think it's reasonable to be confused over this. I was deliberating over buying the iOS app but couldn't see any example of subfolders supported in an iCloud folder.

I think the app description, at least on fsnot.es, should make this clearer (that on iOS, individual folders can be added but they won't show subfolders); would have saved me the time it took to finally get my answer on this closed Github issue.

**Comment by tjatjagithub** [comment]
> Given that the desktop app supports subfolders and it is not stated otherwise that the iOS app doesn't, I think it's reasonable to be confused over this. I was deliberating over buying the iOS app but couldn't see any example of subfolders supported in an iCloud folder.
> 
> I think the app description, at least on fsnot.es, should make this clearer (that on iOS, individual folders can be added but they won't show subfolders); would have saved me the time it took to finally get my answer on this closed Github issue.

Yes, indeed.
And it goes even further:

If the iOS App simply cannot see and do the things that I can do and see with the macOS App, I don't need both of them !
Why use an App on one OS that does not work (the same) on the other OS?

I already deleted all instances on all devices and use iA Writer and Textastic instead!
I am missing the encryption option, but as there is no solution, I cannot really do anything.

**Comment by gingerbeardman** [comment]
Also see #188
