### ISSUE TITLE
Subfolders being shown as folders on iOS

### ISSUE THREAD

**Issue by mzwlevi** [glushchenko/fsnotes#1722]
**Describe your feature request**
I have seen the subfolders on macOS, I purchase iOS today but find it do not show the subfolder, could you add it on iOS?
Thank you!

**Additional context**

![CleanShot 2024-04-19 at 20 11 11@2x](https://github.com/glushchenko/fsnotes/assets/78029539/d55bac8a-706a-4f2e-8a05-d9b1d8854716)
![Screenshot 2024-04-19 at 20 11 21](https://github.com/glushchenko/fsnotes/assets/78029539/f4e17a80-36c4-4b9f-aa65-607bd63289e2)

iOS version is 6.2.3 build 279

**Comment by glushchenko** [comment]
I dont know how to implement it.

https://github.com/glushchenko/fsnotes/issues/1208

**Comment by glushchenko** [comment]
fsnot.es main page:

<img width="1616" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/998bd105-3a50-4808-95ba-645f60007af9">

**Comment by aksonov** [comment]
@glushchenko Thanks for great product! If I implement subfolders for iOS would you add it to main branch?

**Comment by glushchenko** [comment]
@aksonov yes.

**Comment by paulrudy** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1089917?u=cd41ad937df1980f99c966c6b6881dccc6551025&amp;v=4&amp;size=48">@glushchenko](https://github.com/glushchenko) Thanks for great product! If I implement subfolders for iOS would you add it to main branch?

@aksonov just wondering if this is something you're working on?

**Comment by glushchenko** [comment]
@paulrudy 

No, no one wants to spend ~100 hours of development time on a useless feature.

**Comment by paulrudy** [comment]
@glushchenko  Thanks for your reply. I'm curious why you think it's a worthless feature, considering that it's available in the mac version of FSNotes.

I would find it useful in iOS as well.

If it's very difficult to implement, I respect that, but it would clearly a useful feature to some people who have asked for it in this repo, and for people who use nested folders in similar apps.

**Comment by paulrudy** [comment]
@glushchenko I just wanted to follow up to clarify. I wasn't trying to ask you if you were working on this feature, since you already made clear [where you stand](https://github.com/glushchenko/fsnotes/issues/1708) on adding new features.

My intention was just to check in with @aksonov since he had proposed a PR, and you had said that would be acceptable if he made one. The quoted text tagged you, but I wasn't trying to direct the question to you, and didn't mean to offend.

In any case, thank you for an excellent app, and all of your dedication to sharing it with us!
