### ISSUE TITLE
Logo proposal: Fsnotes

### ISSUE THREAD

**Issue by baranpirincal** [glushchenko/fsnotes#197]
Hey, I examined your project (great job by the way) and I can contribute with making a logo design. If you interested please contact me. I am waiting your feedback.  Have a nice day! 😄 

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by glushchenko** [comment]
Hello @baranpirincal, it would be great. Current icon is ugly.

**Comment by baranpirincal** [comment]
@glushchenko Do you have a any idea about design decisions? For example; should it be minimal or 
what colors do you want me to use?

**Comment by glushchenko** [comment]
I wanted to adapt iOS logo, which my girlfriend did, without success. Minimalistic design I really like, but i have no special requirements.

https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/e4/9b/7f/e49b7f77-a8d7-dd16-fbd8-194738503735/AppIcon-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-6.png/230x0w.jpg

**Comment by gingerbeardman** [comment]
@baranpirincal great idea! 

FSNotes is influenced by an old app called Notational Velocity (nv) and a slightly less old app called nvALT. The FS of FSNotes stands for File System because the notes are stored as regular files (rather than a database).

Here are the Apple guidelines describing what makes a great macOS icon: https://developer.apple.com/macos/human-interface-guidelines/icons-and-images/app-icon/

I like the Maps icon. Looking at both the iOS and macOS versions.

**Comment by jeff-h** [comment]
Great work @baranpirincal ! Thanks for contributing this!

Although it's highly subjective, for what they're worth, my thoughts:

* I really like the Futura heading, and your version is nicely kerned :) Looks great beside the icon as you have it. Makes me anticipate a website for this app...
* my favourites are the first two on the second row
    — I'm not sure the "plus" overlay (on row 3) imparts anything useful, so prefer without
    — I feel the second row has an appealing lightness, rather than the outline on the third row versions
* it could be interesting to consider if it would work to rotate that logo upside-down 😀 ; the rounded corner (currently bottom-right) would then infer an 'f' for FSNotes. The ring binder rings would become tabs in the notebook. Just an "out-there" thought, feel free to ignore it...
* I somewhat prefer the un-circled version (for macOS) as it allows the notebook to be larger, but the circled one does also appeal to me. A bunch of Apple's apps' icons are encircled. If you go for the circled, I wonder if a subtler gradient might be cleaner feeling?
*  I actually think the rotation of row 3 number one might be quite appropriate for this app, but don't feel strongly about it either way. The rotated version does look a little like a bird's wing (perhaps off a flying toaster, if you're old-school enough lol), which may or may not be what you're after :)

Overall a great direction... all the app needs then is a new name lol but I rather feel it's too late for that.

**Comment by gingerbeardman** [comment]
I've got some thoughts but I've just woken up from a very good wedding so it is going to be several hours maybe a day. 

I think this is a good start and I'd like to propose a route for further exploration. 

Now for a Bloody Mary.

**Comment by gingerbeardman** [comment]
Also only @glushchenko can decide if it's too late for a new name. 

New name + new icon + new layout + delay release to App Store = possible App Store Feature if I call in a favour 😉

**Comment by glushchenko** [comment]
Application rename is not problem, but new name should be worthy. And i dont have idea, but i’m open for suggestions.

**Comment by jeff-h** [comment]
Swiftnotes? 😜

**Comment by glushchenko** [comment]
@jeff-h already exist

**Comment by glushchenko** [comment]
1) Sadly, mac app store do not support renaming. Guys, i think FSNotes is not too bad. I look to the future with optimism and think we'll get used to it. 

2) Today i register nice domain name for app – fsnot.es

3) We need to choose a logo. Vote please: left – thumbs up , right – heart.

https://f001.backblazeb2.com/file/og-files/Screen-Shot-2018-04-23-20-11-37.png

**Comment by glushchenko** [comment]
@baranpirincal please mail me high res sources.

fluder@icloud.com

**Comment by baranpirincal** [comment]
@glushchenko hey, I sent all variations of my logo design in editable and .PNG format both. Could you please check it?

**Comment by glushchenko** [comment]
Thank you, @baranpirincal. Next FSNotes release will be with new logo.

**Comment by gingerbeardman** [comment]
I hope not too late but I think we could improve on the logo. If there's no rush then please wait until I post a mock-up of my idea on Tuesday.

**Comment by gingerbeardman** [comment]
OK! Thanks for your patience. ✌️

I think FSNotes is fine as a name.

So there are a few points I wanted to raise about how the proposed icon does not adhere to the macOS Human Interface Guidelines (posted earlier). 

- [ ] realistic shape
- [X] unique shape
- [X] recognizable
- [X] simple
- [X] single focus point
- [ ] use color judiciously
- [ ] smooth gradients
- [ ] perspective
- [ ] rotation
- [ ] drop shadow

These means that it does not sit easy amongst other icons IMHO. For me it feels like an initial concept rather than a finished icon - I mean that in the nicest possible way.

Look at the Maps/Pages icon, for example:

![appicons_macos](https://user-images.githubusercontent.com/49612/39176853-c18661b6-47a5-11e8-82d3-c72f4893b0ba.png) ![pages](https://user-images.githubusercontent.com/49612/39177146-67a73fe8-47a6-11e8-933f-b8a8c1ab0786.png)

![appicons_ios](https://user-images.githubusercontent.com/49612/39176855-c19ca5ac-47a5-11e8-9f4d-27634b9d555a.png)  ![ios-pages-app-icon-600x236](https://user-images.githubusercontent.com/49612/39177152-69240d10-47a6-11e8-85bc-5e3f8b4cdb91.png)

To apply this learning to FSNotes, we could have a page with an overlaid element that signifies FSNotes along with a separate simplified icon for iOS.

Quick Mockup:

![fsnotes](https://user-images.githubusercontent.com/49612/39182440-d6726ade-47b4-11e8-9935-4e353546eb7c.png)

![screen shot 2018-04-24 at 11 51 42](https://user-images.githubusercontent.com/49612/39182792-e39de46c-47b5-11e8-8e74-9502eddf7945.png)

Things we'd need to decide:
- Correct drop shadow 
- Symbol to represent "File System" (macOS folder is placeholder)
  - not disk or drive as they are outdated
- Text to use on icon (README.md is placeholder)
  - a famous note rendered as Markdown
- Colours (macOS folder is placeholder)

**Comment by gingerbeardman** [comment]
You can change the App Name in iTunes Connect but only when the app is in an _editable state_, normally as part of submitting a new version. See: https://help.apple.com/itunes-connect/developer/#/dev97865727c

**Comment by jeff-h** [comment]
@gingerbeardman thanks for your work on that — it's helpful to have another perspective. You seem to know the HIG well — can you comment on what the HIG has to say about circular icons on macOS? That seems very common these days, and even a bunch of Apple's own apps do it (App Store, Siri, Launchpad, Safari, Photos, iTunes).

The current Photos app (one of Apple's newer app icons) ticks only the same checkboxes as you listed above for the first proposed FSNotes icon, I think.

**Comment by gingerbeardman** [comment]
@jeff-h that's a good question. It's mentioned as follows:

> **Consider giving your app icon a realistic, unique shape. In macOS, app icons can have the shape of the objects they depict.** A unique outline focuses attention on the object and makes it easy to recognize the icon at a glance. _If necessary, you can use a circular shape to encapsulate a set of images._ Avoid using the rounded rectangle shape that people associate with iOS app icons.

In an old Yosemite-era macOS HIG that I still have in iBooks, circular icons are referenced as follows:

> In icons that use the round graphical style—such as those in iTunes, iBooks, App Store, and Safari—the symbols use the same embossed effect, and the overall shape and use of color are consistent.

Of course, these are only guidelines. 

But I still think that we should shoot for a more refined icon.

**Comment by glushchenko** [comment]
> But I still think that we should shoot for a more refined icon.

I do not mind if someone does it better, but at this moment choice between old icon and new. New seems to me more successful.

**Comment by peavine** [comment]
I didn't participate in this issue, as my design skills are nonexistent, but I like the new logo a lot. It stands out from the crowd and I think that's good. Thanks.

**Comment by baranpirincal** [comment]
@glushchenko  I will re-design it according to comments, maybe it would be better
