### ISSUE TITLE
Note styling

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#20]
I'm wondering what your (longer-term) plans are regarding note text styling.

My hope is you'd consider offering basic style formatting, depending on the chosen file type eg RTF would offer: Bold, Italics, Strikethrough and underline, and Markdown would add H1 to H6. Neither would offer font face or size changes.

**Comment by jeffgeorge** [comment]
Thanks for adding this initial functionality!

To improve feature parity with NV / NVAlt, are there possible considerations to move the pin/unpin key shortcut from ⌘+Y to something else, and move Strikethrough to ⌘+Y?

Maybe move pin/unpin to ⌘+P, since ⌘+P presently crashes FSNotes? (Unless FSNotes plans on implementing Printing, I guess?)

**Comment by williamsmj** [comment]
+1 for moving ⌘+Y to strikethrough.

Please don't use ⌘+P for anything other than print (which FSNotes should implement). There's a widespread OS-wide expectation about what that shortcut does that should not be ignored.

**Comment by jeff-h** [comment]
Even though as far as I know ⌘+Y is fairly unique to nvALT... I'd also love ⌘+Y for strikethrough. It's really handy in my particular useage of nvALT.

The pin idea is really neat — I wonder what other keyboard shortcut would make sense for it?

**Comment by jeffgeorge** [comment]
Thanks for updating this @glushchenko, but I'm having some issues with the RTF implementation. Instead of acting as a Toggle, the new commands just apply a setting, which means in RTF mode you can't un-style text.

Formatting also doesn't seem to be additive anymore. I'm having trouble testing this thoroughly, but in RTF mode once I have something bold, if I ⌘+U to underline it, it underlines but the bold drops. If I try to re-bold it, with ⌘+B nothing happens. If I have underlined text and then try to Italicize it with ⌘+I that works. Selecting it again and trying to ⌘+B to bold the text does nothing. ⌘+U to re-underline it drops the italicization. Still no way to clear formatting altogether.

Obviously this isn't an issue in Markdown mode because it's all plaintext.

**Comment by glushchenko** [comment]
@jeffgeorge, will be fixed in next release.

**Comment by glushchenko** [comment]
@jeffgeorge fixed, 0.16 updated.

**Comment by jeff-h** [comment]
This is really awesome work.

I noticed one oddity — setting a style on a selected piece of text should leave the selected text still selected but it currently deselects it.

**Comment by thiemehennis** [comment]
What about strikethrough? It's greyed out in my installation. Will it be implemented in the future? I could not find a definitive answer in this thread so I decided to reopen it. I use md to save my files.

**Comment by jeff-h** [comment]
Partially related; strikethrough works fine in `rtf` (I don't use `md`).
