### ISSUE TITLE
[REQ] Add GUI or config file - to configure keyboard shortcuts

### ISSUE THREAD

**Issue by ambrosso** [glushchenko/fsnotes#201]
Add GUI or config file - to configure keyboard shortcuts.

**Comment by gingerbeardman** [comment]
You can already do this, for any app,  through MacOS > System Preferences > Keyboard > Shortcuts

FSNotes Preferences also has a couple.

**Comment by peavine** [comment]
I make extensive use of the macOS ability to create keyboard shortcuts in system preferences. However, with FSNotes, this ability is limited in just a few instances because the following menu items are used in FSNotes under both the File and Folder menus:

* Delete
* Rename
* Reveal in Finder

I've tried but have not been successful in creating a shortcut for the second instance of these menu items.

**Comment by gingerbeardman** [comment]
That's a good point. The menu labeling should be distinct and descriptive.

**Comment by peavine** [comment]
Thanks for changing the duplicated menu-item names under the Folder menu.
