### ISSUE TITLE
[REQ] add support for snapshot/versions

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#207]
TextEdit does this well, and I often use it solely for this feature.

**NSFileVersion**
A snapshot of a file at a specific point in time.
https://developer.apple.com/documentation/foundation/nsfileversion

**View and restore past versions of documents**
https://support.apple.com/kb/PH25757

> Many apps automatically save versions of documents as you work on them. At any time, you can browse through document versions and go back to an older version. You can also explicitly save a version.
> 
> A version is saved automatically every hour, or more frequently when you’re making many changes. A version is also saved when you open, save, duplicate, lock, rename, or revert a document.
> 
> Browse, restore, duplicate, and delete versions
> Open the document, then choose File > Revert To > Browse All Versions.
> 
> Click tick marks along the timeline to browse versions.
> 
> Display the version you want, then do one of the following:
> 
> To restore your document to this version, click Restore.
> 
> To duplicate this version in a new document, press and hold the Option key, then click Restore a Copy.
> 
> To delete this version, move the pointer to the top of the screen to show the menu bar, then choose File > Revert To > Delete This Version.
> 
> To leave your document as is, without changes, click Done.
> 
> Explicitly save a version
> Open the document, then choose File > Save.
> 
> To save the document using a different filename, location, or format, press and hold the Option key, then choose File > Save As.
> 
> Revert a document to the last opened version
> Open the document, choose File > Revert To, then choose Last Opened, Last Saved, or Previous Save.
>

**Comment by quinncomendant** [comment]
This would be a nice feature.

In the meantime, since we're just talking about text files, it's easy to use third-party tools to make snapshots of the data store. I use several tools that give me "snapshots" of my notes:

- daily: backup all note files to zip archive under `~/.backup/` via cron script, pruning all backups older than 7 days.
- hourly: cloud backup via [Arq](https://www.arqbackup.com/).
- every 15 mins: back to external drive (if it's connected) via Time Machine.
- every time I hit save in Textmate (my external editor): save a copy of the file to `~/.backup/` with timestamp in filename. I also have a Textmate command that lists all snapshots of the current file. To do this natively in FSNotes, one could create a background service that uses something like [fsmonitor](https://www.npmjs.com/package/fsmonitor) to observe for file changes, then diff with the previously saved snapshot, and if the difference is more than X bytes, create a new snapshot.

**Comment by glushchenko** [comment]
So, guys, I am almost implemented Git solution. This will be available in FSNotes 3.7.0

**Comment by gingerbeardman** [comment]
Can you tell us more?

**Comment by glushchenko** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1089917/64564826-16d42f80-d35b-11e9-9d13-cc3026ee70b0.png">

**Comment by glushchenko** [comment]
You can save version for file at any time manually, or tune auto backup manually.

**Comment by peavine** [comment]
> You can save version for file at any time manually (⌘+s), or tune auto backup manually.

I did the following:

1) Install FSNotes 2.7.

2) Change "Git" preference in FSNotes preferences to "peavine > Working" and "Back up manually".

3) Selected the command-s keyboard shortcut.

After doing the above, a folder was created in my Working folder with the name "b3f8 - Notes.git" and this folder contained a lot of folders with names like hooks, logs, objects, and so on. Why did this happen?

**Comment by gingerbeardman** [comment]
Could that folder be hidden?

Even though this is powered by Git, I think it should all be hidden away from the user.

**Comment by peavine** [comment]
I have my own backup and file-versioning system and don't really need this feature (although I'm sure it's a great enhancement for other people). The issue is that if I inadvertently select command-s when FSNotes is open, the git repository folder is created. Plus it's not hidden. 

Anyways, as a workaround, I changed the git repository folder in FSNotes preferences to the macOS trash, which is a bit kludgey but works well.

**Comment by glushchenko** [comment]
Repositories should not be created in the working directory. Seems like a bug. @gingerbeardman have your tried this feature?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
By default repositories storage here:
```
let applicationSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
let repositories = applicationSupport.appendingPathComponent("Repositories")
```

**Comment by jeff-h** [comment]
Just wondering if this new feature handles pre-existing git repositories, or will it try to create a new one?

Also, from my experience storing notes in git, my git seemed unable (or, hopefully, unconfigured) to tell when a note's creation & modified dates changed. At some point a bug in FSNotes caused all my notes to get the current time as their creation & modified dates, and it was only then that a) I realised that my GIT history was of no help and b) that this information is actually a valuable part of my notes library! Curious whether anyone else has noticed/tested this, and since you're bundling git now, whether there's a way to configure it in a way that's specifically fine-tuned for text notes.

**Comment by glushchenko** [comment]
No, at first .git repositories should not stores in iCloudDrive (default FSNotes storage). At second, bad idea store all backups data in one place.

So default storage is Application Support dir, and this path configurable in preferences.

**Comment by gingerbeardman** [comment]
I have not tried this. I probably do not intend to do so as I use Time Machine which takes care of this need for me. So, if FSNotes Mac used the macOS standard way of doing versions, I would be more inclined use that as it fits into my workflow.

**Comment by peavine** [comment]
I wanted to try out this new feature but don't know how. I made some changes to a note and then selected

File > Save Revision

I then made some additional changes to the note and tried to revert to the saved revision, but there's no menu item for this that I could find.

**Comment by glushchenko** [comment]
@peavine oops, really, i missed it. History will be added in top menu with next release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
@quinncomendant you can open repositories storage and replace current *.git saving same name. History will be adopted

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
@peavine History menu item added in top menu. You can re download last build.

**Comment by peavine** [comment]
I installed the latest build of  3.7.0 and "File > History" works great. I didn't think I would use this much but it is a nice convenience. Thanks.

**Comment by quinncomendant** [comment]
> @quinncomendant you can open repositories storage and replace current *.git saving same name. History will be adopted

Do you mean I need to move my current git directory (`~/Library/Mobile Documents/com~apple~CloudDocs/notes/.git`) to the location of the one created by FSnotes (`~/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories/93d3 - notes.git`)?

**Comment by quinncomendant** [comment]
I'm confused by the automatic back up option setting, `Back up every _1_ hour at _30_ minutes`. It could mean either:

- Back up every 60 minutes, at half-past the hour (00:30, 01:30, 02:30, etc).
- Back up every 90 minutes (00:00, 01:30, 03:00, etc).

Which is it?

I would like to suggest simplifying this option:

```
Back up every ___ [minutes ▿]
```

The `[minutes ▿]` is a select menu containing time units (seconds, hours, minutes, etc).
