### ISSUE TITLE
[REQ] Live Markdown preview panel

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#242]
Would you consider adding a live Markdown preview sidebar, alla [MacDown](https://macdown.uranusjr.com/features/)? Thanks! 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/8772017/40254603-24378974-5ab2-11e8-8578-64bace636e11.png">

**Comment by glushchenko** [comment]
No, use  ⌘ + `

**Comment by kortina** [comment]
Sort of related (because I think I have seen some live preview features work this way)... one issue with the  `⌘ + \`` route is that if you have a long document, and are editing the bottom of the document, when you turn on the Preview feature, the area you are editing may be below the fold requiring you to scroll down to see if your formatting changes look as desired.

Have you considered making the live preview scroll to ensure the line where the cursor in the editor is positioned is in view when you enter the preview mode?
