### ISSUE TITLE
Filter to find unlinked (orphaned) notes?

### ISSUE THREAD

**Issue by peanutputter** [glushchenko/fsnotes#322]
Hi Newbie here,

Supporter of both Mac and iOS app due to active development.   Kudos and keep up the great work.

I am a big fan of the Zettelkasten method which includes highly hyperlinked notes to other notes. Question: is there any way, filter to find notes that are NOT linked to other notes?  In other words, orphan notes?

Thanks in advance,
Tom

**Comment by gingerbeardman** [comment]
It can be done easily for tags, because FSN uses the standard MacOS tags so you can use Finder to do a complex logical search on them. 

For hyperlinks, you should be able to do a "search all" in a good text editor (Sublime?) on your notes folder so that you can see which files don't contain `](` - part of a markdown hyperlink. 

Let us know how you get on. 

I'd not heard of Zettelkasten, very cool, thanks!

**Comment by jeff-h** [comment]
Your "search all" suggestion will only find notes that don't link out to others. I think the original issue is how to find notes that no other note links to, and I can't think of any way to achieve that without specifically writing code to do so.

The logic would go something like this, I guess;

1. go through every note and record every link found
2. go through every note and see if a link to it is found in the aggregate collection made in step 1
3. show any notes which do not have a link

**Comment by gingerbeardman** [comment]
Ah yes, misunderstanding from me.

In that case I would approach it from the shell:
1. find all note links
  - grep all notes containing links
  - extract linked filename
  - correct format of filename
`grep '](' * | cut -d'/' -f 4 | sed -E -e 's/\)/.md/g' -e 's/%20/ /g' | sort > linked.txt`
2. list all notes
`ls -R1 *.md | sort > all.txt`
3. diff
`diff linked.txt all.txt`

😎🤘

**Comment by jeff-h** [comment]
😮
