### ISSUE TITLE
Search/create (command L) does not create a new note if the text is contained in another note

### ISSUE THREAD

**Issue by 30thirteen** [glushchenko/fsnotes#337]
## In nvalt
- If I type 'tuesday' notes CONTAINING the word 'tuesday' show up. 
- If there is not already a note TITLED 'tuesday' pressing return creates a new note with the TITLE 'tuesday

## In fsnotes
- If I type 'tuesday' notes CONTAINING the word 'tuesday' show up. 
- PROBLEM: If there is not a note TITLED 'tuesday,' pressing return DOES NOT create a new note. Instead, it places the cursor inside the top search result.

**Comment by peavine** [comment]
FSNotes will work the way you want if you got to FSNotes preferences, then the User Interface tab, then remove the checkmark from "Note auto selection when body text matched".

**Comment by 30thirteen** [comment]
Thank you for replying.

That didn't work.

I quit and restarted the app after unchecking the box to see if that would
fix it, but it still doesn't work.



*On the web:*
jeffreylong.net <http://www.jeffreylong.net>
jeffreylongstudios.com <http://www.jeffreylongstudios.com>
30thirteen.com <http://www.30thirteen.com>

*Social media:*
Facebook.com/jeffreylong.net
Twitter @30thirteen
Pinterest.com/jeffreyclong
Linkedin: linkedin.com/in/jeffreylong3013

**Comment by gmenzel** [comment]
I see the same problem as @30thirteen. Assuming "Note auto selection when body text matched". is **not** checked, when the search does not match the name of any note, hitting enter creates a new note with the search text as its name. But when the search matches the title of a note, the note is selected, and hitting enter edits that note. This behavior can be recreated with the following steps:

1. Create a new folder in FSNotes.
2. Create a single note in that folder named "foo" with the note text "bar"
3. Search for "ba" and hit enter. A new note named "ba" will be created.
4. Search for "fo" and hit enter. Rather than the expected behavior of a new note name "fo" being created, we find that we are instead editing the note named "foo".

Note also that in step 4 nvAlt provides a completion suggestion which, if accepted, will complete the search text to "foo", at which point the "foo" note will be being edited.

There is perhaps a more general design issue at play here, which is that in nvAlt the contents of the search bar is *always* correlated with the title of the note being displayed and/or edited. This is not the case (yet) for FSNotes.

**Comment by peavine** [comment]
@30thirteen. I repeated this several times with the same result. I don't know why we're seeing different behavior. I'll record a screen video later to demonstrate.

@gmenzel. I followed your four steps and I'm getting the same results. In earlier versions, in your step 4, autocomplete would change "fo" in the search and create bar to "foo", in which case hitting the enter key woulld place the cursor in the editor window for note "foo". With 2.0.8 autocomplete no longer appears to work.

**Comment by peavine** [comment]
@30thirteen. Are you and I doing something different?

![fsnotes_peavine](https://user-images.githubusercontent.com/35905279/44273389-377f9380-a1f4-11e8-9ec7-132d52da844b.gif)

**Comment by glushchenko** [comment]
@30thirteen, this is bug, will be fixed soon,

**Comment by glushchenko** [comment]
@30thirteen @gmenzel fixed in 2.0.9 
https://github.com/glushchenko/fsnotes/releases/download/2.0.9/FSNotes_2.0.9.zip

**Comment by 30thirteen** [comment]
Boom! Fixed!!!



*On the web:*
jeffreylong.net <http://www.jeffreylong.net>
jeffreylongstudios.com <http://www.jeffreylongstudios.com>
30thirteen.com <http://www.30thirteen.com>

*Social media:*
Facebook.com/jeffreylong.net
Twitter @30thirteen
Pinterest.com/jeffreyclong
Linkedin: linkedin.com/in/jeffreylong3013
