### ISSUE TITLE
Checkboxes not rendered 

### ISSUE THREAD

**Issue by benjo2000** [glushchenko/fsnotes#412]
Hi,
thanks for developing fsnotes, i love it.
I found a strange behaviour while trying to use checkboxes in markdown (`- [ ] bla bla`).
While it looks fine in the edit mode, when i toogle preview with cmd + ´ it appeares to be unrendered while everything else is typeseted as it should. See the attached pictures; pic 1 is in edit mode, pic 2 is in preview mode.
Thanks!
![1_fsnotes_unrendered](https://user-images.githubusercontent.com/17175434/48717821-74f02480-ec1a-11e8-98e2-387603c79346.png)
![2_fsnotes_rendered](https://user-images.githubusercontent.com/17175434/48717823-7588bb00-ec1a-11e8-9aff-afdd7bdf8965.png)

**Comment by takacsot** [comment]
I have similar issue. (Actually this is the only issue what stopping me to adapt instead of Boostnote)

Here my version of edit and preview mode

<img width="144" alt="image" src="https://user-images.githubusercontent.com/144732/50660366-d2a8b800-0f9f-11e9-99ee-dcc1f9a1472c.png">

<img width="212" alt="image" src="https://user-images.githubusercontent.com/144732/50660370-d76d6c00-0f9f-11e9-9571-534e06a08f5d.png">

Macos Sierra
fsnotes version: 2.5.5

**Comment by glushchenko** [comment]
Hi @takacsot, thank you for feedback. Will be implemented soon.

**Comment by glushchenko** [comment]
Fixed
