### ISSUE TITLE
"Search and Create" doesn't focus field

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#421]
When I select "Search and Create" from the menu or hit command-L, the search field sort of wiggles but never focuses. Clicking in it works.

FSNotes 2.3.4, OS X 10.13.6
[Command-L Failure Movie.zip](https://github.com/glushchenko/fsnotes/files/2612801/Command-L.Failure.Movie.zip)

**Comment by glushchenko** [comment]
Tryed in clean VirtualBox, works normal https://dsh.re/46c952

**Comment by erikrose** [comment]
It mysteriously started working again, without me doing anything notable. Let's see if it recurs.

**Comment by quinncomendant** [comment]
I have experienced this issue since first using FSNotes months ago, and can reproduce it every time. The problem only exists upon _first launch_ and before the search field _receives focus with a mouse cursor:_

1. Quit, then relaunch FSNotes.
2. Type `⌘L` or select _Search and Create_ from the File menu (the search field focuses and immediately unfocuses).
3. Click just one time in the search field with the mouse cursor.
4. Move the focus somewhere else (e.g., in the note content area).
5. Now `⌘L` and _Search and Create_ will work correctly (focus will remain in the search field).

This happens every time I launch FSNotes. I've just learned to work around this bug by clicking in the search field once with the mouse cursor.

FWIW, here's a [video of the issue on my FSNotes 2.7.3](https://github.com/glushchenko/fsnotes/files/2804319/FSNotes.-.Search.and.Create.bug.mov.zip).

**Comment by quinncomendant** [comment]
@glushchenko, can we re-open this issue?

**Comment by quinncomendant** [comment]
_Search and Create_ works now on first launch, @glushchenko – thanks!

**Comment by glushchenko** [comment]
Thank you for bug reporting

**Comment by erikrose** [comment]
@quinncomendant Thanks so much for figuring out a reproduction!
