### ISSUE TITLE
[REQ] soft tabs

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#436]
Would you consider adding an option to have the tab key insert 4 spaces instead of a tab character when in note editing mode? Thanks!

**Comment by lukaskawerau** [comment]
@glushchenko Is there any chance this could make it into v3? I've had a couple of issues with copy-pasting code from FSNotes to somewhere else because FSNotes had tabs where I'd need soft tabs.

**Comment by glushchenko** [comment]
@lukaskawerau added in FSNotes v3 project, thanks.

**Comment by lukaskawerau** [comment]
This is so great, thank you!

**Comment by glushchenko** [comment]
Added in FSNotes v3

**Comment by quinncomendant** [comment]
@glushchenko, would it be possible for spaces to be used when doing *Shift Left* and *Shift Right* (when "Use 4 spaces…" is checked)? Otherwise, I think this feature is broken: my documents are filling with a mix of spaces and tabs, like this:

<img width="92" alt="Screen Shot 2019-06-11 at 20 38 23" src="https://user-images.githubusercontent.com/6884276/59317560-18715700-8c89-11e9-85a2-397a04f6c761.png">

Also, the option in settings ("Use 4 spaces instead tab") should be written "Use 4 spaces instead of tab".
