### ISSUE TITLE
[REQ] Start with search highlighted? Like nvALT

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#483]
Checking the few bad reviews we have on the App Store...

I noticed that nvALT starts with search highlighted.

Is this something we want to do?

**Comment by peavine** [comment]
I looked at the macOS app store and the overall rating of FSNotes is 4.8 stars out of a possible 5 stars. The lowest rating is 3 stars. That seems pretty good. I read through the written reviews but didn't see any mention of starting the app with search highlighted?

**Comment by gingerbeardman** [comment]
Then reviews are specific to each app store region. 

I seem to remember a website to view them all at once. Will look into that

**Comment by gingerbeardman** [comment]
OK, so this is possible in the App Store backend (iTunes Connect) but for the public there are now less free options.

So, for now, I have created a Slack group with a channel that will collect new reviews as they come in. I don't expect to use Slack for chat, but [feel free to join](https://join.slack.com/t/fsnotes/shared_invite/enQtNTQ0MDk5MDgwNDM4LWVmOGI5NGMzODA3Y2NlYWFmMzU1NWQ4MDM1MzAxNDU3NzVkMzhkYTQ2NTE3NTY3ZDk4YWQ2YzgwOTA1OTU1NmE) to keep an eye on reviews.

**Comment by gingerbeardman** [comment]
So I have found a site, you need to switch between regions to see all reviews but it's OK.

MacOS
https://fnd.io/#/us/mac-app/1277179284-fsnotes-by-oleksandr-glushchenko

iOS
https://fnd.io/#/ud/ios-universal-app/1346501102-fsnotes-manager-by-oleksandr-glushchenko

I'll add this to a Wiki page.

**Comment by keymasterr** [comment]
If I understood it right, you are talking about that behavior of nvAlt when the search field always shows the title of the current note. There is more than one problem this behavior solves:
1. _The most important one:_ when using FSNotes as a hotkey window, you can see the current note in the editor panel, but if you hit enter to edit it further, you suddenly creating a new note and the one you were looking at — disappears from your sight.
2. Now there are two modes: Editor and List-with-Search (you can browse through the notes list with arrows and write anything to the search without switching the focus). But the latter looks like two separate modes because there is no sign that the Search field is active. In nvAlt when you hit Return it means you activated what was in the Search. In FSNotes you are activating the list element if you've chosen one with arrows or creating an empty file if you didn't. It blows my mind to track that hidden modal states. Jeff Raskin is against current behavior :-)
    1. When the focus is on Editor, Search and List highlights should be dimmed. Now it is bright blue in any mode.
        1. My System highlight color is Graphite, FSNotes doesn't follow my system settings in that
3. When the Search field will show the title of the current note, there will be two similar texts: Editor file title and Search field text. That's why there is a one big Search field above both List and Editor in nvAlt:
![image](https://user-images.githubusercontent.com/6844067/52562245-9c642100-2e06-11e9-83a6-303abfbb29c1.png)

**Comment by gingerbeardman** [comment]
@keymasterr what i mean is when I load up nvAlt it looks like this:

![screen shot 2019-02-11 at 12 29 42](https://user-images.githubusercontent.com/49612/52563247-c1ea2e00-2df8-11e9-8e8b-4955c9a95a6f.png)

- search field has focus

but as you mention there are some other things at play:
- search field has most recently viewed note title (so note is highlighted and shown for editing)

I think the keyboard UI in nvALT is still much better than FSNotes

**Comment by peavine** [comment]
Wasn't this change made in closed issue #591 or is this a different issue?

**Comment by gingerbeardman** [comment]
Good spot @peavine thanks
