### ISSUE TITLE
Search speed since 2.9.1

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#518]
In 2.9.0 the search/filter speed is virtually instant, across my ~1,500 notes. In 2.9.1 (and later) it takes a good second or so after each keypress for the filtered results to show. These later releases are slow enough to feel pretty unusable for me.

Is anyone else experiencing this?

**Comment by quinncomendant** [comment]
I'm not experiencing slow results appearing (I only have about 500 notes), but I did notice some other annoying behaviour that may be related:

1. I invoke FSNotes with my global search shortcut.
2. I type a few search words quickly.
3. After a few characters the focus moves into the last visible note and my typing goes into the note.

I'll try to express this as an example, searching for `my search words`:

After invoking FSNotes, I start typing in the search bar:

    🔍[my sea                   ]

Then, somewhere in the note, this appears:

    rch words

That would be expected behavior if I had hit enter or tab after "*my sea*", but I didn't. This is not easy to reproduce, but it does seem more likely to occur if I'm typing fast, with the search results stuttering to appear. This only began sometime in the last few updates.

**Comment by peavine** [comment]
I've been experiencing the issue reported by @quinncomendant for some time. I've never reported it because I never could pin down exactly when it happens, and the thought occurred to me that it might be something I'm doing incorrectly (like inadvertently hitting the enter key).

I never use the global search shortcut, so I don't think it's related to that.

**Comment by quinncomendant** [comment]
@peavine – phew! – I'm not crazy (alone 😉). Since it's not just me having the problem I reported above, I've moved my comment into its own issue (#527), so we don't hijack Jeff's conversation with a possibly unrelated issue.

**Comment by glushchenko** [comment]
Hi @jeff-h, sorry for delayed response. FSNotes v3 take all my time.

I am test FSNotes with 10k notes, and thats working fast.

May be possible troubles with new feature https://github.com/glushchenko/fsnotes/issues/382  Now FSNotes handled all plain text files. Did you have any big files inside storage?

**Comment by jeff-h** [comment]
My biggest note is 23KB :) Anyway, I am glad to say this issue was something local to my Mac! I finally got around to try restarting my Mac (belatedly installing the 10.14.3 update) and the issue has gone away completely. My Mac hadn't been restarted for quite a few months prior to this.
