### ISSUE TITLE
Feature Request: Add an option to disable creating untitled notes

### ISSUE THREAD

**Issue by fi0** [glushchenko/fsnotes#519]
I always to to create notes with a title. Please add an option to disable creating untitled notes.

**Comment by jeanm** [comment]
<kbd>⌘</kbd>+<kbd>N</kbd> could automatically set the focus on the title field rather than the main body.

**Comment by fi0** [comment]
My problem is, sometimes I accidentally clicked on the editor area. But I wasn't intended to create a note.

**Comment by peavine** [comment]
If I understand correctly, I agree with jeanm. This could work as follows:

1) The user selects "File > New" from the top menu or the command-N keyboard shortcut. This would place the focus in what I guess is called the title bar.

2) The note name shown in the title bar would be "Untitled Note". This note name would be highlighted so that the user could type a note name of their choosing. The Finder works this way when creating a new folder.

3) The user selects the Enter key to select "Untitled Note" as the note name. Alternatively, the user types a note name of their choosing and then selects the Enter key to create a note with that name. 

BTW, this is something I raised in #511. I think there should be an easier way to create a new note with a name of the user's choosing.

**Comment by gingerbeardman** [comment]
>My problem is, sometimes I accidentally clicked on the editor area. But I wasn't intended to create a note.

@fi0 that one is covered in #510

**Comment by peavine** [comment]
It seems like @fiO is raising two issues--or perhaps I don't understand. The first issue is creating a new note with a name of the user's choice. The second is the creation of a new note when clicking in the editor.

**Comment by fi0** [comment]
closing this issue because this is a duplicate of #510
