### ISSUE TITLE
"Hide/show notes" in the view menu should by "Hide/show note list"

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#524]
"Note list" is what it's called in UI preferences.

"Notes" is confusing. "Hide notes" makes me think you're going to hide my open note too.

**Comment by peavine** [comment]
That menu item is a bit imprecise. I wonder if it was written that way because "Hide/show notes list" is too long.

A better way of doing this might be to do what most macOS apps do, which is to use "Show" when the UI element (e.g. the sidebar) is hidden and "Hide" when the UI element is shown. Thus:

Show notes list
Hide notes list

BTW, the FSNotes user-interface preferences uses both "Notes List" and "Note List." FWIW I would prefer "Note List."

**Comment by peavine** [comment]
I just noticed that all of the items in the "To do" list for FSNotes v3 are now finished. This version has a lot of good new stuff.

**Comment by peavine** [comment]
I installed FSNotes 3.0 (242) and the menu item "Hide/show note list" isn't too long at all. Looks great. 👍
