### ISSUE TITLE
Multiple folders

### ISSUE THREAD

**Issue by jeremycherfas** [glushchenko/fsnotes#56]
Does fsnotes support multiple folders, for very different topics or, for example, to have a notes archive?

**Comment by jeff-h** [comment]
It doesn't, at present. I have thought about this too, on and off — it would be awesome to be able to sync a folder of notes with a colleague for work, another with family members and another just for me, for example. The UI would need a lot of thought though as I'd hate to share a note with the wrong group of people lol

In terms of the technical side, I'm not up-to-date with @glushchenko's recent work on iCloud integration, but outside of that it doesn't seem an impossible task to add this, although not trivial. 

Re: notes archive; another idea I have had on and off is to provide an "advanced" tab in the prefs where you can specify a shell command to run on certain events eg note added, note deleted, note updated. That could be pretty powerful, I think.

**Comment by jeremycherfas** [comment]
I don't share notes with anyone, but I do want them to be available on all my devices. So mis-sharing would not be an issue for me. I remain hopeful ...

**Comment by glushchenko** [comment]
I began implement this feature request https://dsh.re/f3299 ;-)

**Comment by jeff-h** [comment]
Woah :D 

What are your thoughts on UI for:

* selecting the default storage location for new notes
* visually identifying which notes are in which collection in the notes list

**Comment by mcuix** [comment]
I am at the moment using a work-around to separate groups of notes. I place a common #tag at the top of each note, which means that notes are then visibly grouped together by placing the #tag in the search bar.

**Comment by jeremycherfas** [comment]
Exactly! That's what I want, to be able to have different folders for different purposes, not to sort notes as such.

**Comment by mcuix** [comment]
Look forward to seeing this as an update in the App Store.

**Comment by glushchenko** [comment]
Coming soon, guys :-)

**Comment by jeff-h** [comment]
This is huge!

If you haven't already settled on a UI for this, may I suggest something similar to how 1Password handles multiple "vaults"? Each vault is stored wherever you choose in the filesystem (in Dropbox, or wherever). Then in 1Password's main window, you can either view the items in all vaults combined, or switch between vaults so that the only items accessible are those in the current vault.

<img width="234" alt="screen shot 2017-11-24 at 6 36 33 pm" src="https://user-images.githubusercontent.com/841871/33196961-2d97e2a6-d147-11e7-83d5-4d0d01240361.png">

As you may see in another issue, I'm rather hoping you don't want to implement these as actual folders in the sidebar of the app. I want to feel very confident that I will not accidentally share a note with my work colleague that I meant to share with my wife, for example! I really like the modality of 1Password's solution in this respect.

It also avoids the ambiguity of where new notes should be stored, except for the "All-in-one" view where you'd have to still ask the user, or use the currently selected note to tell you this.

**Comment by glushchenko** [comment]
Hi, guys. Initial build here https://github.com/glushchenko/fsnotes/releases/download/1.1.10/FSNotes.app.zip

**Comment by glushchenko** [comment]
Checkout https://github.com/glushchenko/fsnotes/releases/tag/1.1.11

**Comment by mcuix** [comment]
Just trying out the latest update to the App store. This has been a great addition to the app.

**Comment by jeremycherfas** [comment]
Really impressive; thanks. I wrote [a quick review](https://stream.jeremycherfas.net/2017/dropping-the-cash-to-try-fsnotes).
