### ISSUE TITLE
Asking for password when clicking next to the note title

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#564]
When I click in the blank area next to the note title, FSNotes asks me to enter the password for the current note. I'm not using encrypted notes. 

![Screen Shot 2019-05-03 at 14 18 35](https://user-images.githubusercontent.com/6884276/57161797-11197c80-6db2-11e9-8113-429d1d212980.png)

Is it asking me to *create* a password so the note can be encrypted? If so, the language should be changed to make this clear.

----

*BTW: how do I set up encrypted notes? Is there documentation for this yet? In my settings the `Change Master Password` button is disabled:*

![Screen Shot 2019-05-03 at 14 47 19](https://user-images.githubusercontent.com/6884276/57161993-9a30b380-6db2-11e9-857d-b0f6eba0a889.png)

**Comment by peavine** [comment]
I don't know why you get that dialog when clicking to the left of the note title. To the far right of the note title, there is a padlock and clicking on that will raise the password dialog (see screenshot below).

Note encryption is on a per-note basis and does not have to be enabled. Simply select the note and then select "Lock/unlock" from the right-click or top-level menu.

The master password in FSNotes preferences is only available for biometric unlock (TouchID). I assume (but don't really know) that your computer does not have TouchID and that's why the master password menu item is grayed out.

<img width="650" alt="screenshot" src="https://user-images.githubusercontent.com/35905279/57165499-1f649a00-6dac-11e9-8338-6a6408b14642.png">

**Comment by quinncomendant** [comment]
@peavine, your reply clarifies a lot, thanks.

Probably related to this ticket: my version of FSNotes (3.0.0 (254)) does not display a lock icon –

![Screen Shot 2019-05-04 at 13 07 54](https://user-images.githubusercontent.com/6884276/57183132-1936f200-6e6e-11e9-81e9-151f36b34cd4.png)

**Comment by glushchenko** [comment]
macOS 10.12?

**Comment by quinncomendant** [comment]
I'm on macos 10.13.6

**Comment by peavine** [comment]
That's a puzzle. FWIW, I've included a screenshot below of the FSNotes editor with the password lock icon. I'm on FSNotes 3.0.0 (254) and macOS Mojave.

<img width="564" alt="screenshot" src="https://user-images.githubusercontent.com/35905279/57185099-2d80ec00-6e7a-11e9-8394-ad670f88cf27.png">

**Comment by glushchenko** [comment]
Bug related to 10.13 only, fixed.

**Comment by glushchenko** [comment]
Please try 3.0.3
