### ISSUE TITLE
[BUG] Unexpected behaviour naming and renaming new note

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#569]
1. Enabled "First line as title" option
2. Create new note

note has the following names:
- filesystem: UUID such as _32D5676A-8981-4076-99CD-8110F2CE011F.md_ 
- side bar: Untitled Note
- editor title bar: 32D5676A-8981-4076-99CD-8110F2CE011F

3. Press Cmd+R to rename note
4. Cancel rename by pressing `Escape`

now we have:
- filesystem: UUID such as _32D5676A-8981-4076-99CD-8110F2CE011F.md_ 
- side bar: Untitled Note
- editor title bar: Untitled Note

5. Type a heading, like `# Test Title`
6. Wait a moment

note has the following names:
- filesystem: UUID such as _32D5676A-8981-4076-99CD-8110F2CE011F.md_ 
- side bar: Test Title
- editor title bar: 32D5676A-8981-4076-99CD-8110F2CE011F

**Recommendation**
- Editor title bar needs to be updated sooner than rename
- Side bar note title should also take effect at filename and title bar level

Also see #530

**Comment by jakemkc** [comment]
Right now my workaround is to create new file only through the search field -- works both in Mac and iOS version. 

However, if I am sharing a link in iOS, e.g., twitter to fsnotes, I still have filename shown in the filesystem as those random numbers. Would be great if that can be fixed.

Thanks.

**Comment by jeff-h** [comment]
Sorry I must have missed any discussion around using UUIDs. Surely `Untitled-x` is more Mac-like?

**Comment by gingerbeardman** [comment]
I'm not sure there was a discussion. It used to be Untitled-x but I think there was an increasing problem with clashes? @glushchenko

**Comment by peavine** [comment]
This was briefly discussed in closed issue #530.

**Comment by jakemkc** [comment]
Not sure about others, but this is a little bit awkward to me.

There is no export option in fsnotes and it works more like nvalt. If I can't/don't create notes from the search box, I have to rename every note created, or else when I have to move my notes out through finder, it will be a mix of filenames with UUIDs and proper titles.

**Comment by gingerbeardman** [comment]
>Not sure about others, but this is a little bit awkward to me. ...

@jakemkc I agree

**Comment by sven-gh** [comment]
I'm running into this issue as well. More precisely I have a folder set to Sort by Title
but this does not work because it sorts on file name and not title, similar to this issue: https://github.com/glushchenko/fsnotes/issues/420

Having file name in sync with note title would solve this,
plus agree with above that it would be less awkward and make the files better portable

**Comment by sven-gh** [comment]
I'll add these observations here because even though it's iOS vs. Mac it's perhaps sufficiently related?

- I have "Use first line as title" enabled
- create new note on iOS using the '+' sign
- the note's first line is correctly displayed as note title in the iOS sidebar
- but on Mac this note willl show in the sidebar as "Untitled note" (even though the setting "Use first line as title" is enabled in all places on both iOS and Mac)

other scenario:
- create a note on iOS using the "Search and create". It's just a quick note while on the go that only has title and no content yet
- then on Mac open the note and add content to it. This works fine on Mac (content is added and note title stays the same in both header and side bar)
- but on iOS the note title in the Side bar has updated to the first line that you typed on the Mac
- as a result the note is now showing with different sidebar titles in iOS vs Mac making it hard to find and causing confusion
