### ISSUE TITLE
[REQUEST] - Old Icon

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#586]
The original icon prettier than the new MacOS one I think. :)

**Comment by gingerbeardman** [comment]
Can I confirm that you mean the original icon shown here: https://www.producthunt.com/posts/fsnotes

![0054370D-809C-4CE2-BD70-DF4F371C096C](https://user-images.githubusercontent.com/49612/57569473-8b1eb680-73ed-11e9-92d8-5f6c7751248c.png)

**Comment by peavine** [comment]
It's not the original icon but perhaps he was referring to the icon from #197?

![39087935-8db84764-45b1-11e8-9431-e5d8003e2c6a](https://user-images.githubusercontent.com/35905279/57570674-70cae580-73b9-11e9-8f8f-4a741eeec49f.jpg)

**Comment by hellonoko** [comment]
Ah yes sorry, I mean the version 2 icon Blue with the white stripes and tabs.

**Comment by sven-gh** [comment]
I prefer the mac "thunder" icon though I can see why some people might prefer the previous icon. 

The thunder icon does feel a bit heavy on the eye - probably because the note color goes from yellowish at the top to pinkish at the bottom.

The alternative icon with yellow thunder which you can select from the settings feels a lot "easier" on the eye but then again that one won't stand out as much because yellow thunder is pretty generic.

Also, there might be too heavy of a "shadow" on the icon compared to for instance Apple's own icons and this perhaps makes the thunder icon feel less sharp/polished.

**Comment by gingerbeardman** [comment]
@sven-gh all good points, the thunder icon needed a bit more work but we had to launch. we'll look at it going forward, I think it's safe to say this will not be the last icon for FSNotes, there have been three so far!
