### ISSUE TITLE
[REQUEST] - Allow customization of note preview

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#587]
Are there any plans to allow customization of the look and feel of the note preview?

It would be nice if the markdown preview could be customized by simply providing a .css file (similar to how [typora](https://typora.io) handles themes).

**Comment by jakemkc** [comment]
Not the best way but I think you can modify this file. 

`/Applications/FSNotes.app/Contents/Resources/DownView.bundle/css/down.min.css`

I did simple changes and it works for me.

<img width="292" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/18485734/57932988-18e52080-788a-11e9-8cc0-8244e8623cda.png">

**Comment by BeWe11** [comment]
Adding an option to choose a custom path for the css file (instead of the hard coded one) would allow full customization of the preview window and would barely require any code changes. What do you think @glushchenko ?

**Comment by glushchenko** [comment]
Will be added in next release 😉

**Comment by BeWe11** [comment]
Thanks! Looking forward to it.

**Comment by glushchenko** [comment]
Available in FSNotes 3.2.0

**Comment by Asutu** [comment]
I know this is already closedbut didn't want to start a new issue, because I'm more looking for some help.

I set the Layout note font to Menlo regular and it looks nice in editing mode but when it is rendered the lines are too tight, and I'd like to increase the paragraph line spacing in the preview to double spacing. I copied the `markdown-preview.css` file to a new location and pointed the Markdown Preview CSS advanced preference in FSNotes to this file. Trying to change the `line-height` in the `body` doesn't seem to have any effect on the preview (even after restarting FSNotes). I also tried other solutions that I looked for in the web like creating a `p {line-height: 2}` or `body > p {line-height: 2}` and variations of `em` and `px` and neither did work, but I also don't know CSS and am not sure if I'm doing this correctly (probably not because it's not getting any effect). Can someone help me out with this?

Many thanks.
Pedro
