### ISSUE TITLE
Upper Case → Uppercase  /  Lower Case → Lowercase

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#621]
In English, the [more common spelling](https://english.stackexchange.com/questions/59409/lowercase-lower-case-or-lower-case) of these menu items would be:

- *Make Uppercase*
- *Make Lowercase*

Instead of:

<img width="155" alt="Screen Shot 2019-06-11 at 20 47 48" src="https://user-images.githubusercontent.com/6884276/59318236-e6adbf80-8c8b-11e9-91eb-c35ca6ba801e.png">

**Comment by gingerbeardman** [comment]
If you're up for filing a PR, you can easily edit the affected files directly on GitHub.

https://github.com/glushchenko/fsnotes/search?q=%22upper+case%22&unscoped_q=%22upper+case%22

**Comment by peavine** [comment]
I dont' have a preference as to how this should be done, but in TextEdit macOS Notes, and Script Editor, Apple uses:

Make Upper Case
Make Lower Case
Capitalize

<img width="765" alt="screenshot" src="https://user-images.githubusercontent.com/35905279/59354178-6c0b9100-8cd9-11e9-837b-4142c90619d9.png">

**Comment by gingerbeardman** [comment]
Apparently Upper Case, Uppercase and Upper-Case are all valid English. 

Personally, I use separate words because of the history of the term. Physical letter forms were stored in the upper/lower physical storage cases, ready for typesetting.

https://en.wikipedia.org/wiki/Letter_case
![image](https://user-images.githubusercontent.com/49612/59359223-de09c780-8d25-11e9-9bb3-f1d3dc62cf43.png)

Apple use Upper Case
Microsoft use Uppercase.

**Comment by quinncomendant** [comment]
Ok, I'll concede. It's best to follow standards set by Apple. 

The text editors I use (Textmate and Visual Studio Code) both use the single-word variants. Then, when I saw this n-gram chart, it seemed irrefutable 😜

![cmJLl](https://user-images.githubusercontent.com/6884276/59378995-325b7a00-8d1b-11e9-99ae-432d6baf3a7e.jpg)

Thanks for the history, @gingerbeardman, I have a new appreciation for the Cases.

**Comment by gingerbeardman** [comment]
I hold Microsoft responsible 😆
