### ISSUE TITLE
[REQUEST] Don't use CMD+BACKSPACE to delete note while editing

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#628]
A common hotkey in text apps on Mac is to use <CMD+BACKSPACE> to delete everything in the current line up to the current cursor position.

Example:
```
This is an example sente<cursor_is_here>nce.
```
Usually, pressing <CMD+BACKSPACE> in this situation will result in the following:
```
nce.
```
fsnotes however moves the complete note into the trash!

I think it would be sensible to use the normal behavior of this hotkey while editing. Only when the user is not in edit mode (i.e. there is no cursor set in the document) should the hotkey delete the note.

**Comment by gingerbeardman** [comment]
See https://github.com/glushchenko/fsnotes/issues/596

**Comment by BeWe11** [comment]
Hey @gingerbeardman, thank you for the link.

As I understand the other issue, there was a previous state where fsnotes actually allowed to use <cmd+backspace> for it's intended behavior (deleting line content) while using the same hotkey to delete notes when the focus was in the notes area. However, this feature apparently was bugged and the fix resulted in the hotkey now *always* deleting notes.

I'd argue that the current behavior is still buggy and that having <cmd+backspace> always delete notes is not the intended behavior of that hotkey.

For the sake of clarification, I propose the following behavior:

1. The user is currently **not editing** a note: <cmd+backspace> should delete the currently displayed note.
2. The user is currently **editing** a note: <cmd+backspace> should delete the line content upto the cursor position (normal behavior)

**Comment by gingerbeardman** [comment]
Sure thing.

Meanwhile, you can fix it for your setup by using the info in that other issue.

**Comment by peavine** [comment]
I wanted to get in my 2 cents.

Just by way of background, in the Apple summary of keyboard shortcuts under the heading "Finder and System Shortcuts", the following is shown:

Command-Delete: Move the selected item to the Trash

So, using Command-Delete in FSNotes to move a note to the trash makes a lot of sense and the OP doesn't disagree with this.

The same Apple summary document under "Document shortcuts" does not show Command-Delete at all, although this shortcut is used in TextEdit and other apps to delete from the cursor to the beginning of the line.

I personally would not be in favor of making any change to the Command-Delete shortcut right now because it's not always clear in FSNotes where the focus is at. If Control-Delete takes on a dual purpose, it would be too easy IMO to delete a note when the user intends to delete text.  I suspect the note-highlighting issue is what led jeff-h to request the change he made in issue #220. 

So,  unless it is made as part of a change in note-list highlighting, and FWIW, my personal preference is that no change be made to the Control-Delete keyboard shortcut.

BTW, if the above doesn't make sense, have a look at the macOS Notes app to see how the highlighting differs when the note list has the focus and when the editor has the focus.

The link to the Apple document is:

https://support.apple.com/en-us/HT201236

**Comment by BeWe11** [comment]
Hey @peavine, thanks for your input!

I have to admit I agree with your arguments. Having Command-Delete removing line content is an "artifact" of MacOS using libedit. For the same reason you can use hotkeys like Control-A to go to the line start etc. However, these are not officially supported hotkeys and an app should feel free to redefine these hotkeys as is appropriate.

Still, using Command-Delete to remove line content is so ingrained in my text workflow that having this hotkey delete notes is very annoying for me. Personally, I'd prefer a slightly longer hotkey for note deletion, as I tend to delete notes rather rarely. Thanks to the fix in https://github.com/glushchenko/fsnotes/issues/596 I can do this right now.

I guess the whole issue now reduces to having the ability to redefine hotkeys in fsnotes (which would be a nice addition in general), instead of relying on a workaround. I'm gonna close this issue and create a new feature suggestion. Thank you both!

**Comment by gingerbeardman** [comment]
Also, there is a page in the wiki about redefining keys at a macOS level.

**Comment by glushchenko** [comment]
Obviously it is a bug

**Comment by glushchenko** [comment]
Fixed in 3.3.4

**Comment by peavine** [comment]
> Obviously it is a bug

This is proof of the old saying that one man's bug is another man's feature. :)
