### ISSUE TITLE
files with no extension have issues

### ISSUE THREAD

**Issue by JesseAldridge** [glushchenko/fsnotes#67]
All of the notes I imported from Notational Velocity have no file extension.  This seems to cause strange behavior.  If I have a note called "foo note" and view it in fsnotes it appears to be renamed to "foo note.txt".  If I type "foo note" into the search bar and hit return, a new note called "foo note.md" is created.  Somehow I sometimes end up with two notes with the same name in the fsnotes sidebar.  I try to delete one but nothing happens.  I assume this is related to the above, but I'm not sure how to reproduce it.

**Comment by jeff-h** [comment]
Any idea why your notes have no extension? That doesn't sound right to me.

Are your notes all `.md` or `.rtf` files? If you're confident the files just need a proper extension, and they should all have the same extension, it's actually possible to bulk-rename files in macOS. Select a bunch of your notes, right-click them and choose "Rename x Items...". You can then add the appropriate file extension to the notes.

Secondly, be aware that FSNotes monitors the filesystem for changes in your notes folder(s). If you add a note file via the finder or another app, FSNotes will detect that change and update itself. This currently does not detect filename changes, nor file deletes.

Finally, it's possible FSNotes has the (erroneous) assumption that no note files will have the same filename, but a different extension eg `mynote.rtf` and `mynote.md`. That's just a guess though — be interested in someone testing it. FSNotes strips the file extension before displaying the note filename in the note list, so if two notes have the same filename but different extensions they will appear as the same note name in the note list.

**Comment by JesseAldridge** [comment]
> Any idea why your notes have no extension?

Because that's how Notational Velocity stores them (I assume).  The "import" process was literaly just me creating a folder called "fsnotes_files" and copy/pasting all the files from my NV directory.  

Actually I just checked again and the majority of them now have a ".txt" extension.  lol.  Not sure if I was mistaken before or if they changed or what.  I do still have some with no file extension.  And several with a ".md" extension.  

>  right-click them and choose "Rename x Items..."

Omg, that's new.   I looked for this feature once and it didn't exist.  Cool.

I think the best solution might be just to require a single file extension -- ".md" maybe -- and ignore every file that doesn't have that extension.  It would be somewhat inconvenient for users -- but it would simplify the code and remove a bunch of edge cases.

**Comment by jeff-h** [comment]
I can clarify that (for me at least) nvALT did create notes with extensions, at least when you choose RTF as the storage for your notes. I did as you did, just copied all my note files into a new folder and pointed FSNotes at it.

> the best solution might be just to require a single file extension

This would certainly have been easier to code but unfortunately it won't work because FSNotes handles multiple file types, even simultaneously (as indeed you've discovered). I personally am super-pleased @glushchenko implemented it this way because I really, really wanted RTF and not many notes apps support that, weirdly.

I do think in your case you may have brought forward a bit of an odd history into FSNotes — perhaps nvALT messed your notes up at some point in the past. 

However I also think you've exposed some poor edge-case handling of note files in FSNotes, so if you're able to mess around with various combinations it would be great to know if you could narrow that down to a replicable scenario.

**Comment by JesseAldridge** [comment]
Hmm, trying to reproduce this on my personal machine.  But apparently FSNotes doesn't run on OS X 10.11.  So there's another feature request I guess.

In the meantime I think I'm going to switch to using my own personal project, which is too simple to break:  https://github.com/JesseAldridge/toothbrush

**Comment by jeff-h** [comment]
Ha, love it :) Takes the whole "power-user's note app" to a new level :)

**Comment by glushchenko** [comment]
Files with no extension invisible for FSNotes.
