### ISSUE TITLE
How Apple kills indie developers

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#695]
Over 2 year I am develop FSNotes app, over 1000 commits pushed. I write code almost every day and this is really hard work. 

FSNotes available for free in **brew** and **GitHub**. I love this app. One motivation point for me was AppStore sales, and this is now ruined by Apple.

This message written after 50 days awaiting approving my iOS app – FSNotes Manager.

### Case history

50 days ago I received this message in AppStore Connect:

> Aug 6, 2019 at 6:45 AM
> From Apple
> Hello,
> 
> We are unable to continue this app’s review because your Apple Developer Program account is currently under investigation for not following the App Store Review Guidelines’ Developer Code of Conduct

> During our investigation, we will not review any apps you submit. Once we have completed our investigation, we will notify you via Resolution Center. Due to the nature of the investigation you will be ineligible to receive an expedited review until the investigation is completed.
> 
> We do not require any additional information from you at this time, nor do we have any additional details to share. We appreciate your continued patience during our investigation.
> 
> Best regards,
> 
> App Store Review

I tried to appeal and got this:

> We understand your concern regarding this investigation. However, your account is still under investigation and no action has been taken against it at this time. We are investigating your apps, account, and any related accounts to ensure compliance with the App Store Review Guidelines, Developer Code of Conduct, and Apple Developer Program License Agreement. 
> 
> Once we have completed our investigation, we will notify you via Resolution Center of any next steps. Due to the nature of the investigation you will be ineligible to receive an expedited review until the investigation is completed.
> 
> If we require any additional information about your app or account, we will contact you. We appreciate your continued patience during our investigation.

No any additional info. WTF?

Letter written by bot, and you can Google it by key words https://forums.developer.apple.com/thread/116331

Many people with locked apps awaiting response from Apple. App store team silent from 1 to 3 month, and then unlock (?) reviewing process without any explanations. All these people paid for membership 99 $ and get nothing in results.

This is OK, App Store Team?

I am tried to connect via developers support page, and got same – nothing.

> Hello Oleksandr, 
> 
> I understand that you do not agree with the way the investigation is being carried out. However, until the investigation in to your account is competed no apps under your account will be reviewed. 
> 
> I know that you would like information to share with your users regarding your app, but until the investigation is completed I will not have any updates or additional information to share.
> 
> Thank you for your continued patience throughout the investigation. 

I think it's time to explain to the developers, what going on, Apple?

Please share and repost this.

https://news.ycombinator.com/edit?id=21084209
https://www.reddit.com/r/apple/comments/d9o10b/how_apple_kills_indie_developers/

**Comment by jpantuso** [comment]
Are you 100% certain you have not violated anything?
https://developer.apple.com/app-store/review/guidelines/

It is super annoying that it has been such a long time and they aren't communicating to you. This sort of thing can be life threatening for an indy developer with a family.

**Comment by sfermigier** [comment]
@jpantuso How can he be sure of anything if they don't give him any useful information?

**Comment by glushchenko** [comment]
@jpantuso I'm not 100% sure of course.  But why not respond?  :( Very sad. FSNotes not best of the best, but not worst.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dessant** [comment]
The best way to change Apple's attitude is to sue them. You have paid for a developer account, and they are esentially denying you service for that account, and causing financial loss for your project.

https://www.reddit.com/r/apple/comments/cgi7ro/i_took_apple_to_court_and_won_twice_water_damaged/

**Comment by lucasverra** [comment]
hang in there. As they say in France, "Bon courage !"

<img width="311" alt="image" src="https://user-images.githubusercontent.com/11323803/65722669-f9b69500-e0ac-11e9-9a7c-0082e56c3fc5.png">

**Comment by BernhardBln** [comment]
You seem to be back 😉

**Comment by UnforbiddenYet** [comment]
@glushchenko Ти певен що дійсно не порушив нійких норм чи правил?
Я б тобі радив писати їм листи із проханням розʼяснення на пошту, в твіттер і різні канали звʼязку. 

Я про твоє нещастя дізнався із твіттера HN - https://twitter.com/newsycombinator/status/1177312393229152256. Почни тред на HN в коментарях, можливо хтось із спільноти мав схожу проблему і допоможе. 

Удачі!

**Comment by churchofthought** [comment]
Hang in there bub. Could just be a mistake

**Comment by jupiterkenji** [comment]
This is not good; I also read about app that has big disadvantage because apple has similar product. I reckon we need public mobile app platform.

**Comment by petercunha** [comment]
I hate that these things are practically automated by bots -- developer have _very_ little recourse when it comes to disputing these claims with an actual human at Apple.

I hope everything clears up soon for you, best of luck @glushchenko

**Comment by glushchenko** [comment]
@petercunha thank you 👍🏻

@UnforbiddenYet дякую за підтримку 🇺🇦

**Comment by BernhardBln** [comment]
Hm maybe I got this wrong, but when I open your app in the app store, at least it seems I could click the buy button? Or did they not suspend selling your current app, but only updating it?

**Comment by wmealing** [comment]
When you build for a walled garden monoculture, you should not be surprised when you find the wall or worse.. when the wall finds you.  Open platforms are a better choice for developing on and at least you have options when things go south.

Good luck, i somehow feel as though the sunken cost fallacy will keep developers on this platform for longer than it deserves to live.

**Comment by scottleey** [comment]
guys - You have to recognise that Apple is competing against you. They have all the incentive to put you under investigation to advance their own interest. The platform who purportedly is helping you has an app that is your competitor. what do you think is going to happen when they have the leeway to do whatever they want? of course my claim is without any grounds but I wouldnt be surprised if there's some motive around that.

**Comment by davidglassborow** [comment]
discussion on hn: https://news.ycombinator.com/item?id=21084209

**Comment by gingerbeardman** [comment]
This is so disheartening! It is guilty until proven innocent. 

I've had similar experiences as a seller on eBay: when a buyer reports you they react in favour of the buyer because buyers make their business model work. 

I suspect it's the same here, that Apple have received some sort of complaint about the iOS app (given that the macOS app is unaffected) and the automatic "guilty until proven innocent" system has been activated. And sadly the only thing to do is wait for it to finish. It could be something like waiting 60 or 90 days without any further complaints of the same nature. You could hope for intervention by a sympathetic App Store employee or rep, but I don't know how likely that will be. 

To add insult to injury there is also the fact that this is an open source app and dishonest people are cloning it and selling it, and Apple are slow to take them down if they do at all.

**Comment by iszlailorand** [comment]
It's simple, all the lookalike companies... don't care about this kind of situations, don't care at all. They will delay you by default and delay times are at the max limit 2-3 months... because: "they have a lot of request" and they don't have enough employees... but they have record revenues and they brag about them... what a paradoxal situation. If you pass this "small app" status and reach miliions of users, the next step is a small meeting where they audit your app... and multiply the value of your app with a number between 5-10 and reach you with "an offer that you can't refuse" and block every good willing app on the market, or change the initial idea of the app... that is modern censorship.

**Comment by julian-goldsmith** [comment]
@wmealing: Open platforms are definitely preferable for developers, but don't have anywhere near as many users.  At the moment, if you want to reach the vast majority of mobile users, you have to go through either the App Store or the Play Store.

**Comment by hmans** [comment]
The bank always wins.

**Comment by Pusnow** [comment]
How about [AltStore](https://altstore.io)?

**Comment by glushchenko** [comment]
Finally update approved without any clarifications.

In AppStore connect i am still see this error:

![4A04444E-5E0D-4425-B9DF-F2157E09106B](https://user-images.githubusercontent.com/1089917/66016675-43a1df80-e4e0-11e9-9ab9-900eafaded3c.png)

Fucking Apple.

**Comment by gingerbeardman** [comment]
Where does the "1 unresolved iOS issue" link take you?

**Comment by matchavez** [comment]
Purchased MacOS in support.

**Comment by glushchenko** [comment]
@gingerbeardman to resolution center ...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wmealing** [comment]
> @wmealing: Open platforms are definitely preferable for developers, but don't have anywhere near as many users. At the moment, if you want to reach the vast majority of mobile users, you have to go through either the App Store or the Play Store.

 There are other options and while not as popular would have had significant more clout if developers decided to use them.    The trade off for 'more users' was not a big decision when the iP* devices were first being made, developers made the decision then that the walled garden was more tempting than the alternatives.

**Comment by RaduRomanov** [comment]
Same issue here. Yesterday I had two app submissions: 1 was an update to an existing app and 1 brand new app upload. 

After few hours since both apps got rejected and had the same message, they said that the investigation was complete but the apps can't be approved since mimics existing apps on the App Store.

I remove those 2 apps complete from my account. Today I uploaded an update to another app that I had for over a year and I do constant updates on that app. Suddenly they sent me the same message for this app today, saying the the account is under investigation. I never had issues with this specific app being updated.

**Comment by Haibo-Zhou** [comment]
Same issue for me today, I'm from China. Just create my 1st app using almost 3 months. Then they just reject my app and start investigating my account? WTF. At least they should provide additional info about what they expect, not only ask me to wait.

**Comment by RaduRomanov** [comment]
UPDATE:
I received a new message from Apple. I hope it helps those on this thread.

`Hello,

Thank you for your continued patience. 

We are writing to let you know that we have completed our investigation of your Apple Developer Program account. Upon further investigation, we found that your app does not comply with the following guidelines:

Guideline 4.3 - Design

We noticed that your app provides the same feature set as other apps submitted to the App Store; it simply varies in content or language, which is considered a form of spam.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.`

**Comment by abdalmonem** [comment]
@RaduRomanov in just tow days !, that's so good , i saw a lot of topics in appleDevoloperForm about this issue , some developers keep waiting for 3 months !

**Comment by Haibo-Zhou** [comment]
Update my status, Apple just approve my app 3 hours ago. It just take 4 days for the approval, I submit the version on last Thursday. Maybe I'm lucky! 

**In email:**
"Congratulations! We're pleased to let you know that your app, Vanilla Music, has been approved for the App Store. Once your app has been released, it can take up to 24 hours before your app becomes available on the App Store. "

Then after 24 hrs, I should could see my app in App Store.

**Comment by abdalmonem** [comment]
also me after 7 days waiting , i got a message from apple telling me that they end the investigation

**Comment by glushchenko** [comment]
This is very quick 😳 Lucky guy

**Comment by juanradark** [comment]
Apple only cares about money, not the quality of the AppStore. In the past, indie developers have created great games and utilities. 
But now, if you are a small company or an individual if they don't like something about your app. An employee or just the automated system decides to investigate your account for 3 months, which means the end for your business. Or just remove your developer account without any explanation. They don't investigate Facebook or Google apps, even knowing that they don't follow the guidelines about privacy.

**Comment by gingerbeardman** [comment]
Apple locked out somebody newsworthy

https://daringfireball.net/linked/2019/11/20/rambo-developer-account

https://rambo.codes/personal/2019/11/20/apple-has-locked-me-out-of-my-developer-account.html

**Comment by z31r4m** [comment]
Did Apple ever explain why @glushchenko was “currently under investigation for not following the App Store Review Guidelines’ **Developer Code of Conduct**?”

This seems to be the core issue.

WHERE is this “Code of Conduct” explicitly stated and published on Apple’s site?

Will developers with no relation to AppStore be denied Notarization if they violate this non-binding “Code?”

This is why I won’t develop anything Apple related except for personal use.

**Comment by graywen24** [comment]
> I have not read the entire thing, but hopefully this is just a mistake, hang in there. As they say in France, "Bon courage !"
> 
> <img alt="image" width="311" src="https://user-images.githubusercontent.com/11323803/65722669-f9b69500-e0ac-11e9-9a7c-0082e56c3fc5.png">

also haning there...

**Comment by sdrygalski** [comment]
Is it solved already?

**Comment by gingerbeardman** [comment]
Yes

**Comment by Roen-Ro** [comment]
I came to this issue on Dec 2019, When i renewed my developer account and submitted my new app for review, then the next morning i received the under investigation message from resolution center.
even though they said i can do nothing but waiting for apple's response, but i still tried to reply them some message, tell them that i have a similar app which is functionally with this new one, but they are target for different users.
Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store
https://apps.apple.com/cn/app/id1486738485

我也遇到了同样的问题，2019年年底的时候，不过现在解决了，但是当我尝试给朋友上传一个app壳（用他的新账户），我经过了层层伪装，而且做了一些功能，今天还是收到了这个回复。

**Comment by graywen24** [comment]
> I came to this issue on Dec 2019, When i renewed my developer account and submitted my new app for review, then the next morning i received the under investigation message from resolution center.
> even though they said i can do nothing but waiting for apple's response, but i still tried to reply them some message, tell them that i have a similar app which is functionally with this new one, but they are target for different users.
> Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store
> https://apps.apple.com/cn/app/id1486738485
> 
> 我也遇到了同样的问题，2019年年底的时候，不过现在解决了，但是当我尝试给朋友上传一个app壳（用他的新账户），我经过了层层伪装，而且做了一些功能，今天还是收到了这个回复。

你这个等了多久 才approve的呀。。我等了快2个月了。。还是same

**Comment by graywen24** [comment]
> Yes

So just wait and wait 3 months plus and they will approve? Any other thing we can do? I submit few times already and show in review immediately rejected.

**Comment by graywen24** [comment]
> Same issue for me today, I'm from China. Just create my 1st app using almost 3 months. Then they just reject my app and start investigating my account? WTF. At least they should provide additional info about what they expect, not only ask me to wait.

any update?

**Comment by gingerbeardman** [comment]
> immediately rejected

this is a different issue

**Comment by glushchenko** [comment]
> Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store

5 days vs almost 3 month in my case. And i still dont know why it happens.

**Comment by dungnt109** [comment]
I got the same message from Apple today. I am not sure if the message is actually sent by a human reviewer or by bot. I am so frustrated now.

**Comment by dungnt109** [comment]
I have received the same message from Apple. I am not sure if it sent by a human reviewer or by a bot.

**Comment by graywen24** [comment]
> > Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store
> 
> 5 days vs almost 3 month in my case. And i still dont know why it happens.

really frustrated ... I am the same case as you.... I have to have plan B and ask my friend to pushlish my app for my client now.. no choice

**Comment by graywen24** [comment]
> I have received the same message from Apple. I am not sure if it sent by a human reviewer or by a bot.

by bot.. definitely... and no one can ask for support... even you buy 10000 iphone

**Comment by Roen-Ro** [comment]
> > I came to this issue on Dec 2019, When i renewed my developer account and submitted my new app for review, then the next morning i received the under investigation message from resolution center.
> > even though they said i can do nothing but waiting for apple's response, but i still tried to reply them some message, tell them that i have a similar app which is functionally with this new one, but they are target for different users.
> > Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store
> > https://apps.apple.com/cn/app/id1486738485
> > 我也遇到了同样的问题，2019年年底的时候，不过现在解决了，但是当我尝试给朋友上传一个app壳（用他的新账户），我经过了层层伪装，而且做了一些功能，今天还是收到了这个回复。
> 
> 你这个等了多久 才approve的呀。。我等了快2个月了。。还是same

很快，就四五天

**Comment by Roen-Ro** [comment]
> > Then about 5 days later my new app changed to in review status and then approved the next morning, now it is sale on app store
> 
> 5 days vs almost 3 month in my case. And i still dont know why it happens.

It may because i responded them through resolution center, may be, not for sure

**Comment by HouHangLei** [comment]
My application "Frog warehouse" received the same notification half a month ago and it is now available for sale. I explained the code logic complaint that may cause misunderstandings in machine review. My application passed after 12 days.

**Comment by gingerbeardman** [comment]
> I explained the code logic complaint that may cause misunderstandings in machine review.

Please tell us more

**Comment by HouHangLei** [comment]
> > 我解释了代码逻辑上的抱怨，这可能会导致对机器审查的误解。
> 
> 请告诉我们更多@HouHangLei

I have code in my code to determine whether the user installs the first day. If it is installed on the first day, some logic will not be executed. It may be that these codes caused the investigation. But I ’m not sure if this explanation worked. @gingerbeardman

**Comment by HouHangLei** [comment]
> > I explained the code logic complaint that may cause misunderstandings in machine review.
> 
> Please tell us more @HouHangLei

I have code in my code to determine whether the user installs the first day. If it is installed on the first day, some logic will not be executed. It may be that these codes caused the investigation. But I ’m not sure if this explanation worked. @gingerbeardman

**Comment by tavakoli-ali** [comment]
I got this message from apple and this is my first account and first app !!!!
this is like accusation in court room: 


Hello,

We are unable to continue this app’s review because your Apple Developer Program account is currently under investigation for not following the App Store Review Guidelines’ Developer Code of Conduct.

Common practices that may lead to an investigation include, but are not limited to:

- Inaccurately describing an app or service
- Misleading app content
- Engaging in inauthentic ratings and reviews manipulation
- Providing misleading customer support responses
- Providing misleading responses in Resolution Center
- Engaging in misleading purchasing or bait-and-switch schemes
- Engaging in other dishonest or fraudulent activity within or outside of the app

During our investigation, we will not review any apps you submit. Once we have completed our investigation, we will notify you via Resolution Center. 

We do not require any additional information from you at this time, nor do we have any additional details to share. We appreciate your continued patience during our investigation.

Best regards

**Comment by FarhanSaikh** [comment]
> I got this message from apple and this is my first account and first app !!!!
> this is like accusation in court room:
> 
> Hello,
> 
> We are unable to continue this app’s review because your Apple Developer Program account is currently under investigation for not following the App Store Review Guidelines’ Developer Code of Conduct.
> 
> Common practices that may lead to an investigation include, but are not limited to:
> 
>     * Inaccurately describing an app or service
> 
>     * Misleading app content
> 
>     * Engaging in inauthentic ratings and reviews manipulation
> 
>     * Providing misleading customer support responses
> 
>     * Providing misleading responses in Resolution Center
> 
>     * Engaging in misleading purchasing or bait-and-switch schemes
> 
>     * Engaging in other dishonest or fraudulent activity within or outside of the app
> 
> 
> During our investigation, we will not review any apps you submit. Once we have completed our investigation, we will notify you via Resolution Center.
> 
> We do not require any additional information from you at this time, nor do we have any additional details to share. We appreciate your continued patience during our investigation.
> 
> Best regards

I got the same thing today. I don't know what they are trying to do.
Without any info they said , they are investigating my account.

**Comment by tavakoli-ali** [comment]
> > I got this message from apple and this is my first account and first app !!!!
> > this is like accusation in court room:
> > Hello,
> > We are unable to continue this app’s review because your Apple Developer Program account is currently under investigation for not following the App Store Review Guidelines’ Developer Code of Conduct.
> > Common practices that may lead to an investigation include, but are not limited to:
> > ```
> > * Inaccurately describing an app or service
> > 
> > * Misleading app content
> > 
> > * Engaging in inauthentic ratings and reviews manipulation
> > 
> > * Providing misleading customer support responses
> > 
> > * Providing misleading responses in Resolution Center
> > 
> > * Engaging in misleading purchasing or bait-and-switch schemes
> > 
> > * Engaging in other dishonest or fraudulent activity within or outside of the app
> > ```
> > 
> > 
> > During our investigation, we will not review any apps you submit. Once we have completed our investigation, we will notify you via Resolution Center.
> > We do not require any additional information from you at this time, nor do we have any additional details to share. We appreciate your continued patience during our investigation.
> > Best regards
> 
> I got the same thing today. I don't know what they are trying to do.
> Without any info they said , they are investigating my account.

let me know if you get new answers from Apple .

**Comment by netluxe** [comment]
@FarhanSaikh @tavakoli-ali 

Out of curiosity, what type of apps are you having this issue with?  These are both the first apps you have submitted on your developer account?

The only thing that I can think of (and I hate to think that this would be the case, but knowing how awful Apple have become over the last few years especially, I wouldn't doubt it), is that they are sending BS messages like this out to people via an automated process, when it is a new developer account and a first-time application submission.  At least this would somewhat make sense, not that I think it makes any sense, but from a logical standpoint I can at least follow their line of BS rationalization...if you understand what I mean here.  I have a friend working at Apple who formerly worked within the larger App Store team, and from what I was told (this was ~18 months or so ago, but I'm sure it's still the same now as it was then), that they had been dealing with issues of not having enough competent employees capable of doing a proper manual review of an app's codebase for potentially malicious or sketchy/illegal stuff, in addition to screening for the usual crap that people try to pass thru into the platform of the store all the time.  So, I could see them justifying it to themselves that it's "okay to have some automated bot send out these super vague, accusatory messages to developers who enrich our platform, because at worst, it'll 'inconvenience' them for a little while...and we're Apple, we have a trillion dollar valuation, so what the hell do we care anyway?", and use this bogus "code of conduct" allegation -- _which, note, may or may not be the issue causing the holdup in the first place (!!)_ -- to try and buy their understaffed review team some more time to look over your apps properly.

Now again, I'll stress that I have no idea if this is what's happening or not, but it's really the only thing I can even think up right now.  It's very strange, do keep us updated.

As an aside, it would seem to lend credence to the claims my friend made of them being completely short-staffed (his direct quote being "in a major way") when I am perusing the App Store quite often nowadays and notice tons of BLATANTLY fake reviews pushing up these scumbag developers who are all trying to make quick cash by tricking some teenagers who have their parent's credit card tied to their apple IDs into signing up for an unintended subscription that re-bills at something ridiculous like $9.99/US a week or even some of them have the gall of trying to do a "3 day free trial" after which you get billed something like $56-60 USD for a year (and not even all the features, at that).  This is super prevalent with a certain subset of video applications, if you spend enough time on the App Store as I do, then you'll surely know exactly the sort of apps I'm talking about.  I would name names but they seem to change names so frequently that it'd be kinda pointless, but you can tell these apps because all of the reviews are 5 stars and they are almost ALWAYS written by users whose usernames (or least their display name in the review) is some weird obviously computer generated or imagined full first and last name - never anything like you see with real reviews - and while they have gotten a bit better at making them a bit less obvious lately, if you take even a few minutes to read over the reviews you'll notice that oftentimes the app they claim to be reviewing isn't even the one that they've named in their rave review, or they talk about features/functionality that clearly is from another app.  Also, these apps all seem to be using the same base template.  Probably some UI kit that is being sold or shared on some piracy site, and they get whoever they know with the minimal amount of proficiency in swift to put together a 'new' version of the app.  I've also heard some people claim (though tbh I have no idea if this is true or even possible) that some of these apps are requesting access to people's photos/videos, and are using the permission to upload stuff from the library surreptitiously, in hopes of finding something scandalous or risque or whatever.

Ugh, I've already typed far too much here.  Yeah, just saying, if this kind of crap I mentioned above is going on - and there is stuff like open outright spam that you tend to see written on disused/abandoned wordpress site comment sections or forums with no active userbase anymore, etc. lately all over the reviews of apps with a decent amount of downloads/users sometimes, then it makes me think the stuff about them having such low employee numbers for this part of the business has to be true.
