### ISSUE TITLE
4.0.4 regression: odd cursor and selected note behaviour

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#734]
**Describe the bug**
Whenever I use the arrow keys the current note is deselected. <kbd>up</kbd> <kbd>down</kbd> <kbd>left</kbd> <kbd>right</kbd> all do this. Additionally, the alternating striping in the notes list is toggled each time the cursor press causes the note to be deselected.

**To Reproduce**
1. create a new note, or edit an existing one (tested with `rtf`)
2. press an arrow key

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.1
 - FSNotes version: 4.0.4

**Comment by floodfish** [comment]
I'm experiencing a similar issue. The note also sometimes becomes deselected when inserting cursor manually (with mouse pointer).

**Comment by hanche** [comment]
I am seeing the same on macOS 10.14.6. But not consistently! I was going to test if this happened with cursor movement using ^F and ^B as well, and it didn't. But afterwards, I couldn't even reproduce the problem anymore, at least not until I made a small edit. Then I saw it again upon using an arrow key, but only once. Definitely an *intermittent* bug, at least for me.

**Comment by glushchenko** [comment]
@jeff-h can you make video? I don't understand core of the problem ...

**Comment by hanche** [comment]
I was thinking I could make a video, but right now is one of those times I can't reproduce the problem. Let me try to describe it in words:

You go to a note to edit it: On the left you have the sidebar, then you have the note list with your note selected, and in the right panel you have the text of the note. Clicking the mouse somewhere in the right panel, or typing an arrow key, or sometimes any edit, will once in a while deselect the note in the note list, while in the right panel where the text of the note used to be, there is now just the empty panel with the FSNotes logo in it.

When the bug bites, it can be very persistent: It may take five or six attempts before you can position the cursor, and a few more attempts to make even a simple edit, with the right panel going blank every time and the note deselected. At other times, all seems perfectly normal for a long time.

Wild, totally unsupported speculation: Could it be icloud-related? I suggest that because I have been having quite a bit of trouble with icloud lately. But of course, it could be coincidence.

**Comment by jeff-h** [comment]
Thanks @hanche for the clear description. Bit hard to tell when I pressed the arrow keys, but if you look closely you can actually see the cursor change position very briefly before the note is deselected.

![2019-11-10 11-14-00 2019-11-10 11_16_34](https://user-images.githubusercontent.com/841871/68535711-ade55400-03ab-11ea-9871-6c721dac641c.gif)

Unlike others, this never behaves any other way for me, and it happens regardless of using the arrow keys or <kbd>^</kbd><kbd>F</kbd> and <kbd>^</kbd><kbd>B</kbd>.

**Comment by glushchenko** [comment]
Thank you @jeff-h , i will try to fix this asap

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Guys, anyone can try 4.0.5?

https://github.com/glushchenko/fsnotes/releases/download/4.0.5/FSNotes_4.0.5.zip

**Comment by Aetles** [comment]
4.0.5 solved it for me!

**Comment by hanche** [comment]
Seems to work for me too, but since the problem was intermittent for me it is too early to say.

**Comment by jeff-h** [comment]
Fixed for me, and it was not in the least intermittent :)

**Comment by floodfish** [comment]
Seems to have fixed it for me, too.

**Comment by floodfish** [comment]
@glushchenko I was experiencing this on TXT files, not RTF. But either way, it does seem to be fixed in 4.0.5.

**Comment by jeff-h** [comment]
Thanks @glushchenko — I think this is resolved.
