### ISSUE TITLE
Love FSNotes, but going back to nvALT

### ISSUE THREAD

**Issue by TannerTechnical** [glushchenko/fsnotes#892]
So another day, another FSN point release, and another round of trying to decipher the visual and functional issues newly introduced.

I do like FSNotes - a lot. This is not a critique in any way of the authors or their goals.

But I can no longer take the constant flow of bugs with each release. I think the project overall is in danger of becoming mired in complexity caused by feature-creep. It's becoming a lot of work just to enter a note, assign a tag, assign a folder, then close and re-open FSN just to be sure the item was created correctly.

None of that with nvALT. Just type and forget it. It's captured. I **trust** it to save the file - every time. I **trust** that searching works - every time. The item is never mis-named to some random UID. It doesn't get placed in the wrong folder. It always shows in searches. URL links always work and don't display blank or incorrect notes.

Anyway, I do wish the FSN good luck with their project. I hope to come back one day and find the alternative to nvALT that was originally envisioned.

**Comment by glushchenko** [comment]
Why not? Bye

**Comment by sloria** [comment]
As a counterpoint, I'm moving _from_ nvalt to FSNotes and have been happy with it so far. nvalt is great, but the lack of multi-folder support keeps me from using it for anything outside a single use case (my reading notebook). FSNotes' support for multiple folders means I can have the fast editing and search experience for all my notes.

> complexity caused by feature-creep

On the contrary, I think FSnotes has a well-scoped featureset that is clearly borne out of thorough competitive analysis as well as the author "scratching their own itch". As a result, FSNotes is featureful without feeling bloated.

I've discovered a number of features that I wasn't originally looking for but have since become very useful, including:

- Locked/encrypted notes. Ensures I don't accidentally share a sensitive note
- Code blocks. Allows me to store snippets
- Graceful inline image handling. Many plaintext note apps like nvalt come up short when it comes to images. Using an `i/` directory is a very clever solution that _works_.
- Importing sketches from iphone/ipad. Super useful for whiteboarding and diagramming

On top of this, the author is very actively working on the project and is responsive to feedback.

**Comment by glushchenko** [comment]
0 is not just digit. This is numbers of bug report from @TannerTechnical. So I'm not very upset guys.
