### ISSUE TITLE
Checkboxes only render after navigating away from note

### ISSUE THREAD

**Issue by sloria** [glushchenko/fsnotes#895]
**Describe the bug**

TODO lists don't render checkboxes immediately. They only become checkboxes if you navigate to another note then return to the note.

**To Reproduce**

![Screen Recording 2020-05-14 at 04 03 PM](https://user-images.githubusercontent.com/2379650/81980386-82625100-95fc-11ea-9855-738af9fd38b2.gif)

**Expected behavior**

Checkboxes are rendered immediately

**Actual behavior**

Checkboxes are only rendered after navigating away and back to the note.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.3.2

**Comment by glushchenko** [comment]
⌘ - T ?

**Comment by sloria** [comment]
⌘ - T does work; thanks for showing me that. I'll use that from now on, so no urgency on my end to fix this.

For comparison, Bear renders a checkbox when you type `- `, which is strange behavior in its own way, since I'd expect that to render a bulleted list.

![Screen Recording 2020-05-15 at 09 17 AM](https://user-images.githubusercontent.com/2379650/82054540-17ad2600-968d-11ea-9383-238d3e933a60.gif)

Notion renders a checkbox after typing `- []`, which is what I was expecting in FSNotes.

![Screen Recording 2020-05-15 at 09 20 AM](https://user-images.githubusercontent.com/2379650/82054752-6bb80a80-968d-11ea-9ab6-ee9f97b76fb7.gif)

**Comment by CodeBrauer** [comment]
Since this is already the case with GitHub and many other GFM editors, I assumed it was a standard feature. [According to the spec](https://github.github.com/gfm/#task-list-items-extension-), it's actually an extension, which I didn't know.

As a developer who works in GitHub/GitLab etc. more often, it is common to use this syntax. Also, you could then easily import GFM Markdown copy/paste so that to-dos are also taken over

**Comment by glushchenko** [comment]
PR appreciated
