### ISSUE TITLE
New (single) line breaks not possible in Preview mode

### ISSUE THREAD

**Issue by scottbickell** [glushchenko/fsnotes#917]
**Describe the bug**
Single line breaks display as expected in Edit mode, but disappear in Preview mode.

**To Reproduce**
1. Type a single line. Press Return key to create a new line. Type a second line. Press Return to create a new line, etc.

**Expected behavior**
I expect the breaks to show in Preview mode. They do not.

**Actual behavior**
The line breaks disappear and all the copy displays on a single line instead of multiple lines.

**Workaround**
No workaround other that to use double spacing to get new lines

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
![Screen Shot 2020-06-10 at 3 15 04 PM](https://user-images.githubusercontent.com/6173095/84319721-b06c7f80-ab2d-11ea-95ae-6838cc364b26.png)
![Screen Shot 2020-06-10 at 3 17 53 PM](https://user-images.githubusercontent.com/6173095/84319762-c5e1a980-ab2d-11ea-985e-84f3a0d370c2.png)

 - OS version: 10.15.5
 - FSNotes version: 4.3.3

**Additional context**

**Comment by relikd** [comment]
Actually I wanted to create a new issue for this "fixed" behavior. Now it seems unlikely to change again :(
Because I would like to have that previous behavior, which is also default markdown formatting. Newlines usually do not create a <br in html. Unless you place two spaces at the end of the line. I usually write each sentence in a new line to have better comparability in git diffs so I can easily see what changes I made.

@glushchenko would it be possible to have a checkbox to switch between those two intended behaviors?
