### ISSUE TITLE
First Line = Title = Filename.txt

### ISSUE THREAD

**Issue by deltakilosierra** [glushchenko/fsnotes#929]
**Restore Behavior of First Line = Title = Filename in Finder**
I'm missing the old nvAlt functionality described above. The extra step of renaming the file, something I can recognize when I need to look for it outside of FSNotes is killing my productivity. I'm not sure if this is something that's been changed or if I can't just find the settings to make it behave this way.

**This should be the case on both macOS and iOS**
Consistent naming across platforms would be critical.

(New to Git, hope I did this right.)

**Comment by gizmometer** [comment]
I would love this!

**Comment by andybyte** [comment]
Me too. Is this possible to take the first line as the filename (for me the extension would be whatever I set in the preferences).

Or is the hash-filename essential? 

I understand there are issues if the filename already exists but I would prefer a pop-up with a warning rather than manually renaming files because hash names are not helpful in other applications unless they use the first line too.

**Comment by oldsj** [comment]
It looks like this feature is present in iOS but not on macOS.
iOS
Settings -> General -> Files Naming -> Auto rename by title

**Comment by glushchenko** [comment]
Guys, this implemented on iOS already, and this will be implemented on macOS in near future. Thanks.

**Comment by glushchenko** [comment]
Added here https://github.com/glushchenko/fsnotes/releases/download/4.5.2b/FSNotes_4.5.2.zip

**Comment by glushchenko** [comment]
Dupe #837 #831
